// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: table.proto

package storage2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of deletion file, intended as a way to increase efficiency of the storage of deleted row
// offsets. If there are sparsely deleted rows, then ARROW_ARRAY is the most efficient. If there
// are densely deleted rows, then BITMAP is the most efficient.
type DeletionFile_DeletionFileType int32

const (
	// A single Int32Array of deleted row offsets, stored as an Arrow IPC file with one batch and
	// one column. Has a .arrow extension.
	DeletionFile_ARROW_ARRAY DeletionFile_DeletionFileType = 0
	// A Roaring Bitmap of deleted row offsets. Has a .bin extension.
	DeletionFile_BITMAP DeletionFile_DeletionFileType = 1
)

// Enum value maps for DeletionFile_DeletionFileType.
var (
	DeletionFile_DeletionFileType_name = map[int32]string{
		0: "ARROW_ARRAY",
		1: "BITMAP",
	}
	DeletionFile_DeletionFileType_value = map[string]int32{
		"ARROW_ARRAY": 0,
		"BITMAP":      1,
	}
)

func (x DeletionFile_DeletionFileType) Enum() *DeletionFile_DeletionFileType {
	p := new(DeletionFile_DeletionFileType)
	*p = x
	return p
}

func (x DeletionFile_DeletionFileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeletionFile_DeletionFileType) Descriptor() protoreflect.EnumDescriptor {
	return file_table_proto_enumTypes[0].Descriptor()
}

func (DeletionFile_DeletionFileType) Type() protoreflect.EnumType {
	return &file_table_proto_enumTypes[0]
}

func (x DeletionFile_DeletionFileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeletionFile_DeletionFileType.Descriptor instead.
func (DeletionFile_DeletionFileType) EnumDescriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{8, 0}
}

// UUID type. encoded as 16 bytes.
type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

// Manifest is a global section shared between all the files.
type Manifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All fields of the dataset, including the nested fields.
	Fields []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// Schema metadata.
	SchemaMetadata map[string][]byte `protobuf:"bytes,5,rep,name=schema_metadata,json=schemaMetadata,proto3" json:"schema_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Fragments of the dataset.
	Fragments []*DataFragment `protobuf:"bytes,2,rep,name=fragments,proto3" json:"fragments,omitempty"`
	// Snapshot version number.
	Version uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// The file position of the version auxiliary data.
	//   - It is not inheritable between versions.
	//   - It is not loaded by default during query.
	VersionAuxData uint64 `protobuf:"varint,4,opt,name=version_aux_data,json=versionAuxData,proto3" json:"version_aux_data,omitempty"`
	// The version of the writer that created this file.
	//
	// This information may be used to detect whether the file may have known bugs
	// associated with that writer.
	WriterVersion *Manifest_WriterVersion `protobuf:"bytes,13,opt,name=writer_version,json=writerVersion,proto3" json:"writer_version,omitempty"`
	// If present, the file position of the index metadata.
	IndexSection *uint64 `protobuf:"varint,6,opt,name=index_section,json=indexSection,proto3,oneof" json:"index_section,omitempty"`
	// Version creation Timestamp, UTC timezone
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional version tag
	Tag string `protobuf:"bytes,8,opt,name=tag,proto3" json:"tag,omitempty"`
	// Feature flags for readers.
	//
	// A bitmap of flags that indicate which features are required to be able to
	// read the table. If a reader does not recognize a flag that is set, it
	// should not attempt to read the dataset.
	//
	// Known flags:
	// * 1: deletion files are present
	// * 2: row ids are stable and stored as part of the fragment metadata.
	// * 4: use v2 format (deprecated)
	// * 8: table config is present
	ReaderFeatureFlags uint64 `protobuf:"varint,9,opt,name=reader_feature_flags,json=readerFeatureFlags,proto3" json:"reader_feature_flags,omitempty"`
	// Feature flags for writers.
	//
	// A bitmap of flags that indicate which features must be used when writing to the
	// dataset. If a writer does not recognize a flag that is set, it should not attempt to
	// write to the dataset.
	//
	// The flag identities are the same as for reader_feature_flags, but the values of
	// reader_feature_flags and writer_feature_flags are not required to be identical.
	WriterFeatureFlags uint64 `protobuf:"varint,10,opt,name=writer_feature_flags,json=writerFeatureFlags,proto3" json:"writer_feature_flags,omitempty"`
	// The highest fragment ID that has been used so far.
	//
	// This ID is not guaranteed to be present in the current version, but it may
	// have been used in previous versions.
	//
	// For a single fragment, will be zero. For no fragments, will be absent.
	MaxFragmentId *uint32 `protobuf:"varint,11,opt,name=max_fragment_id,json=maxFragmentId,proto3,oneof" json:"max_fragment_id,omitempty"`
	// Path to the transaction file, relative to `{root}/_transactions`. The file at that
	// location contains a wire-format serialized Transaction message representing the
	// transaction that created this version.
	//
	// This string field "transaction_file" may be empty if no transaction file was written.
	//
	// The path format is "{read_version}-{uuid}.txn" where {read_version} is the version of
	// the table the transaction read from (serialized to decimal with no padding digits),
	// and {uuid} is a hyphen-separated UUID.
	TransactionFile string `protobuf:"bytes,12,opt,name=transaction_file,json=transactionFile,proto3" json:"transaction_file,omitempty"`
	// The file position of the transaction content. None if transaction is empty
	// This transaction content begins with the transaction content length as u32
	// If the transaction proto message has a length of `len`, the message ends at `len` + 4
	TransactionSection *uint64 `protobuf:"varint,21,opt,name=transaction_section,json=transactionSection,proto3,oneof" json:"transaction_section,omitempty"`
	// The next unused row id. If zero, then the table does not have any rows.
	//
	// This is only used if the "stable_row_ids" feature flag is set.
	NextRowId uint64 `protobuf:"varint,14,opt,name=next_row_id,json=nextRowId,proto3" json:"next_row_id,omitempty"`
	// The data storage format
	//
	// This specifies what format is used to store the data files.
	DataFormat *Manifest_DataStorageFormat `protobuf:"bytes,15,opt,name=data_format,json=dataFormat,proto3" json:"data_format,omitempty"`
	// Table config.
	//
	// Keys with the prefix "lance." are reserved for the Lance library. Other
	// libraries may wish to similarly prefix their configuration keys
	// appropriately.
	Config map[string]string `protobuf:"bytes,16,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Metadata associated with the table.
	//
	// This is a key-value map that can be used to store arbitrary metadata
	// associated with the table.
	//
	// This is different than configuration, which is used to tell libraries how
	// to read, write, or manage the table.
	//
	// This is different than schema metadata, which is used to describe the
	// data itself and is attached to the output schema of scans.
	TableMetadata map[string]string `protobuf:"bytes,19,rep,name=table_metadata,json=tableMetadata,proto3" json:"table_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The base paths of data files.
	//
	// This is used to determine the base path of a data file. In common cases data file paths are under current dataset base path.
	// But for shallow cloning, importing file and other multi-tier storage cases, the actual data files could be outside of the current dataset.
	// This field is used with the `base_id` in `lance.file.File` and `lance.file.DeletionFile`.
	//
	// For example, if we have a dataset with base path `s3://bucket/dataset`, we have a DataFile with base_id 0, we get the actual data file path by:
	// base_paths[id = 0] + /data/ + file.path
	// the key(a.k.a index) starts from 0, increased by 1 for each new base path.
	BasePaths []*BasePath `protobuf:"bytes,18,rep,name=base_paths,json=basePaths,proto3" json:"base_paths,omitempty"`
	// The branch of the dataset. None means main branch.
	Branch        *string `protobuf:"bytes,20,opt,name=branch,proto3,oneof" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{1}
}

func (x *Manifest) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Manifest) GetSchemaMetadata() map[string][]byte {
	if x != nil {
		return x.SchemaMetadata
	}
	return nil
}

func (x *Manifest) GetFragments() []*DataFragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

func (x *Manifest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Manifest) GetVersionAuxData() uint64 {
	if x != nil {
		return x.VersionAuxData
	}
	return 0
}

func (x *Manifest) GetWriterVersion() *Manifest_WriterVersion {
	if x != nil {
		return x.WriterVersion
	}
	return nil
}

func (x *Manifest) GetIndexSection() uint64 {
	if x != nil && x.IndexSection != nil {
		return *x.IndexSection
	}
	return 0
}

func (x *Manifest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Manifest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Manifest) GetReaderFeatureFlags() uint64 {
	if x != nil {
		return x.ReaderFeatureFlags
	}
	return 0
}

func (x *Manifest) GetWriterFeatureFlags() uint64 {
	if x != nil {
		return x.WriterFeatureFlags
	}
	return 0
}

func (x *Manifest) GetMaxFragmentId() uint32 {
	if x != nil && x.MaxFragmentId != nil {
		return *x.MaxFragmentId
	}
	return 0
}

func (x *Manifest) GetTransactionFile() string {
	if x != nil {
		return x.TransactionFile
	}
	return ""
}

func (x *Manifest) GetTransactionSection() uint64 {
	if x != nil && x.TransactionSection != nil {
		return *x.TransactionSection
	}
	return 0
}

func (x *Manifest) GetNextRowId() uint64 {
	if x != nil {
		return x.NextRowId
	}
	return 0
}

func (x *Manifest) GetDataFormat() *Manifest_DataStorageFormat {
	if x != nil {
		return x.DataFormat
	}
	return nil
}

func (x *Manifest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Manifest) GetTableMetadata() map[string]string {
	if x != nil {
		return x.TableMetadata
	}
	return nil
}

func (x *Manifest) GetBasePaths() []*BasePath {
	if x != nil {
		return x.BasePaths
	}
	return nil
}

func (x *Manifest) GetBranch() string {
	if x != nil && x.Branch != nil {
		return *x.Branch
	}
	return ""
}

// external dataset base path
type BasePath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// This is an alias name of the base path, it is optional.
	// When we use shallow clone and the target version is a tag, the tag name will be set here.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Flag indicating whether this path is a dataset root path or file directory:
	// - true:  Path is a dataset root (actual files under subdirectories like `data`, '_deletions')
	// - false: Path is a direct file directory (scenario like importing files)
	IsDatasetRoot bool `protobuf:"varint,3,opt,name=is_dataset_root,json=isDatasetRoot,proto3" json:"is_dataset_root,omitempty"`
	// Note: This absolute path will be directly used by Path:parse(),
	Path          string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasePath) Reset() {
	*x = BasePath{}
	mi := &file_table_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasePath) ProtoMessage() {}

func (x *BasePath) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasePath.ProtoReflect.Descriptor instead.
func (*BasePath) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{2}
}

func (x *BasePath) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BasePath) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BasePath) GetIsDatasetRoot() bool {
	if x != nil {
		return x.IsDatasetRoot
	}
	return false
}

func (x *BasePath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Auxiliary Data attached to a version.
// Only load on-demand.
type VersionAuxData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key-value metadata.
	Metadata      map[string][]byte `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionAuxData) Reset() {
	*x = VersionAuxData{}
	mi := &file_table_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionAuxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionAuxData) ProtoMessage() {}

func (x *VersionAuxData) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionAuxData.ProtoReflect.Descriptor instead.
func (*VersionAuxData) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{3}
}

func (x *VersionAuxData) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metadata describing an index.
type IndexMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID of an index. It is unique across all the dataset versions.
	Uuid *UUID `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The columns to build the index. These refer to file.Field.id.
	Fields []int32 `protobuf:"varint,2,rep,packed,name=fields,proto3" json:"fields,omitempty"`
	// Index name. Must be unique within one dataset version.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The version of the dataset this index was built from.
	DatasetVersion uint64 `protobuf:"varint,4,opt,name=dataset_version,json=datasetVersion,proto3" json:"dataset_version,omitempty"`
	// A bitmap of the included fragment ids.
	//
	// This may by used to determine how much of the dataset is covered by the
	// index. This information can be retrieved from the dataset by looking at
	// the dataset at `dataset_version`. However, since the old version may be
	// deleted while the index is still in use, this information is also stored
	// in the index.
	//
	// The bitmap is stored as a 32-bit Roaring bitmap.
	FragmentBitmap []byte `protobuf:"bytes,5,opt,name=fragment_bitmap,json=fragmentBitmap,proto3" json:"fragment_bitmap,omitempty"`
	// Details, specific to the index type, which are needed to load / interpret the index
	//
	// Indices should avoid putting large amounts of information in this field, as it will
	// bloat the manifest.
	//
	// Indexes are plugins, and so the format of the details message is flexible and not fully
	// defined by the table format.  However, there are some conventions that should be followed:
	//
	//   - When Lance APIs refer to indexes they will use the type URL of the index details as the
	//     identifier for the index type.  If a user provides a simple string identifier like
	//     "btree" then it will be converted to "/lance.table.BTreeIndexDetails"
	//   - Type URLs comparisons are case-insensitive.  Thereform an index must have a unique type
	//     URL ignoring case.
	IndexDetails *anypb.Any `protobuf:"bytes,6,opt,name=index_details,json=indexDetails,proto3" json:"index_details,omitempty"`
	// The minimum lance version that this index is compatible with.
	IndexVersion *int32 `protobuf:"varint,7,opt,name=index_version,json=indexVersion,proto3,oneof" json:"index_version,omitempty"`
	// Timestamp when the index was created (UTC timestamp in milliseconds since epoch)
	//
	// This field is optional for backward compatibility. For existing indices created before
	// this field was added, this will be None/null.
	CreatedAt *uint64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	// The base path index of the data file. Used when the file is imported or referred from another dataset.
	// Lance use it as key of the base_paths field in Manifest to determine the actual base path of the data file.
	BaseId        *uint32 `protobuf:"varint,9,opt,name=base_id,json=baseId,proto3,oneof" json:"base_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexMetadata) Reset() {
	*x = IndexMetadata{}
	mi := &file_table_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMetadata) ProtoMessage() {}

func (x *IndexMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMetadata.ProtoReflect.Descriptor instead.
func (*IndexMetadata) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{4}
}

func (x *IndexMetadata) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *IndexMetadata) GetFields() []int32 {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *IndexMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexMetadata) GetDatasetVersion() uint64 {
	if x != nil {
		return x.DatasetVersion
	}
	return 0
}

func (x *IndexMetadata) GetFragmentBitmap() []byte {
	if x != nil {
		return x.FragmentBitmap
	}
	return nil
}

func (x *IndexMetadata) GetIndexDetails() *anypb.Any {
	if x != nil {
		return x.IndexDetails
	}
	return nil
}

func (x *IndexMetadata) GetIndexVersion() int32 {
	if x != nil && x.IndexVersion != nil {
		return *x.IndexVersion
	}
	return 0
}

func (x *IndexMetadata) GetCreatedAt() uint64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *IndexMetadata) GetBaseId() uint32 {
	if x != nil && x.BaseId != nil {
		return *x.BaseId
	}
	return 0
}

// Index Section, containing a list of index metadata for one dataset version.
type IndexSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []*IndexMetadata       `protobuf:"bytes,1,rep,name=indices,proto3" json:"indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexSection) Reset() {
	*x = IndexSection{}
	mi := &file_table_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexSection) ProtoMessage() {}

func (x *IndexSection) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexSection.ProtoReflect.Descriptor instead.
func (*IndexSection) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{5}
}

func (x *IndexSection) GetIndices() []*IndexMetadata {
	if x != nil {
		return x.Indices
	}
	return nil
}

// A DataFragment is a set of files which represent the different columns of the same
// rows. If column exists in the schema of a dataset, but the file for that column does
// not exist within a DataFragment of that dataset, that column consists entirely of
// nulls.
type DataFragment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of a DataFragment is unique within a dataset.
	Id    uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Files []*DataFile `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	// File that indicates which rows, if any, should be considered deleted.
	DeletionFile *DeletionFile `protobuf:"bytes,3,opt,name=deletion_file,json=deletionFile,proto3" json:"deletion_file,omitempty"`
	// A serialized RowIdSequence message (see rowids.proto).
	//
	// These are the row ids for the fragment, in order of the rows as they appear.
	// That is, if a fragment has 3 rows, and the row ids are [1, 42, 3], then the
	// first row is row 1, the second row is row 42, and the third row is row 3.
	//
	// Types that are valid to be assigned to RowIdSequence:
	//
	//	*DataFragment_InlineRowIds
	//	*DataFragment_ExternalRowIds
	RowIdSequence isDataFragment_RowIdSequence `protobuf_oneof:"row_id_sequence"`
	// Types that are valid to be assigned to LastUpdatedAtVersionSequence:
	//
	//	*DataFragment_InlineLastUpdatedAtVersions
	//	*DataFragment_ExternalLastUpdatedAtVersions
	LastUpdatedAtVersionSequence isDataFragment_LastUpdatedAtVersionSequence `protobuf_oneof:"last_updated_at_version_sequence"`
	// Types that are valid to be assigned to CreatedAtVersionSequence:
	//
	//	*DataFragment_InlineCreatedAtVersions
	//	*DataFragment_ExternalCreatedAtVersions
	CreatedAtVersionSequence isDataFragment_CreatedAtVersionSequence `protobuf_oneof:"created_at_version_sequence"`
	// Number of original rows in the fragment, this includes rows that are now marked with
	// deletion tombstones. To compute the current number of rows, subtract
	// `deletion_file.num_deleted_rows` from this value.
	PhysicalRows  uint64 `protobuf:"varint,4,opt,name=physical_rows,json=physicalRows,proto3" json:"physical_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFragment) Reset() {
	*x = DataFragment{}
	mi := &file_table_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFragment) ProtoMessage() {}

func (x *DataFragment) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFragment.ProtoReflect.Descriptor instead.
func (*DataFragment) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{6}
}

func (x *DataFragment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataFragment) GetFiles() []*DataFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DataFragment) GetDeletionFile() *DeletionFile {
	if x != nil {
		return x.DeletionFile
	}
	return nil
}

func (x *DataFragment) GetRowIdSequence() isDataFragment_RowIdSequence {
	if x != nil {
		return x.RowIdSequence
	}
	return nil
}

func (x *DataFragment) GetInlineRowIds() []byte {
	if x != nil {
		if x, ok := x.RowIdSequence.(*DataFragment_InlineRowIds); ok {
			return x.InlineRowIds
		}
	}
	return nil
}

func (x *DataFragment) GetExternalRowIds() *ExternalFile {
	if x != nil {
		if x, ok := x.RowIdSequence.(*DataFragment_ExternalRowIds); ok {
			return x.ExternalRowIds
		}
	}
	return nil
}

func (x *DataFragment) GetLastUpdatedAtVersionSequence() isDataFragment_LastUpdatedAtVersionSequence {
	if x != nil {
		return x.LastUpdatedAtVersionSequence
	}
	return nil
}

func (x *DataFragment) GetInlineLastUpdatedAtVersions() []byte {
	if x != nil {
		if x, ok := x.LastUpdatedAtVersionSequence.(*DataFragment_InlineLastUpdatedAtVersions); ok {
			return x.InlineLastUpdatedAtVersions
		}
	}
	return nil
}

func (x *DataFragment) GetExternalLastUpdatedAtVersions() *ExternalFile {
	if x != nil {
		if x, ok := x.LastUpdatedAtVersionSequence.(*DataFragment_ExternalLastUpdatedAtVersions); ok {
			return x.ExternalLastUpdatedAtVersions
		}
	}
	return nil
}

func (x *DataFragment) GetCreatedAtVersionSequence() isDataFragment_CreatedAtVersionSequence {
	if x != nil {
		return x.CreatedAtVersionSequence
	}
	return nil
}

func (x *DataFragment) GetInlineCreatedAtVersions() []byte {
	if x != nil {
		if x, ok := x.CreatedAtVersionSequence.(*DataFragment_InlineCreatedAtVersions); ok {
			return x.InlineCreatedAtVersions
		}
	}
	return nil
}

func (x *DataFragment) GetExternalCreatedAtVersions() *ExternalFile {
	if x != nil {
		if x, ok := x.CreatedAtVersionSequence.(*DataFragment_ExternalCreatedAtVersions); ok {
			return x.ExternalCreatedAtVersions
		}
	}
	return nil
}

func (x *DataFragment) GetPhysicalRows() uint64 {
	if x != nil {
		return x.PhysicalRows
	}
	return 0
}

type isDataFragment_RowIdSequence interface {
	isDataFragment_RowIdSequence()
}

type DataFragment_InlineRowIds struct {
	// If small (< 200KB), the row ids are stored inline.
	InlineRowIds []byte `protobuf:"bytes,5,opt,name=inline_row_ids,json=inlineRowIds,proto3,oneof"`
}

type DataFragment_ExternalRowIds struct {
	// Otherwise, stored as part of a file.
	ExternalRowIds *ExternalFile `protobuf:"bytes,6,opt,name=external_row_ids,json=externalRowIds,proto3,oneof"`
}

func (*DataFragment_InlineRowIds) isDataFragment_RowIdSequence() {}

func (*DataFragment_ExternalRowIds) isDataFragment_RowIdSequence() {}

type isDataFragment_LastUpdatedAtVersionSequence interface {
	isDataFragment_LastUpdatedAtVersionSequence()
}

type DataFragment_InlineLastUpdatedAtVersions struct {
	// If small (< 200KB), the row latest updated versions are stored inline.
	InlineLastUpdatedAtVersions []byte `protobuf:"bytes,7,opt,name=inline_last_updated_at_versions,json=inlineLastUpdatedAtVersions,proto3,oneof"`
}

type DataFragment_ExternalLastUpdatedAtVersions struct {
	// Otherwise, stored as part of a file.
	ExternalLastUpdatedAtVersions *ExternalFile `protobuf:"bytes,8,opt,name=external_last_updated_at_versions,json=externalLastUpdatedAtVersions,proto3,oneof"`
}

func (*DataFragment_InlineLastUpdatedAtVersions) isDataFragment_LastUpdatedAtVersionSequence() {}

func (*DataFragment_ExternalLastUpdatedAtVersions) isDataFragment_LastUpdatedAtVersionSequence() {}

type isDataFragment_CreatedAtVersionSequence interface {
	isDataFragment_CreatedAtVersionSequence()
}

type DataFragment_InlineCreatedAtVersions struct {
	// If small (< 200KB), the row created at versions are stored inline.
	InlineCreatedAtVersions []byte `protobuf:"bytes,9,opt,name=inline_created_at_versions,json=inlineCreatedAtVersions,proto3,oneof"`
}

type DataFragment_ExternalCreatedAtVersions struct {
	// Otherwise, stored as part of a file.
	ExternalCreatedAtVersions *ExternalFile `protobuf:"bytes,10,opt,name=external_created_at_versions,json=externalCreatedAtVersions,proto3,oneof"`
}

func (*DataFragment_InlineCreatedAtVersions) isDataFragment_CreatedAtVersionSequence() {}

func (*DataFragment_ExternalCreatedAtVersions) isDataFragment_CreatedAtVersionSequence() {}

type DataFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the root relative to the dataset's URI.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The ids of the fields/columns in this file.
	//
	// When a DataFile object is created in memory, every value in fields is assigned -1 by
	// default. An object with a value in fields of -1 must not be stored to disk. -2 is
	// used for "tombstoned", meaning a field that is no longer in use. This is often
	// because the original field id was reassigned to a different data file.
	//
	// In Lance v1 IDs are assigned based on position in the file, offset by the max
	// existing field id in the table (if any already). So when a fragment is first created
	// with one file of N columns, the field ids will be 1, 2, ..., N. If a second fragment
	// is created with M columns, the field ids will be N+1, N+2, ..., N+M.
	//
	// In Lance v1 there is one field for each field in the input schema, this includes
	// nested fields (both struct and list).  Fixed size list fields have only a single
	// field id (these are not considered nested fields in Lance v1).
	//
	// This allows column indices to be calculated from field IDs and the input schema.
	//
	// In Lance v2 the field IDs generally follow the same pattern but there is no
	// way to calculate the column index from the field ID.  This is because a given
	// field could be encoded in many different ways, some of which occupy a different
	// number of columns.  For example, a struct field could be encoded into N + 1 columns
	// or it could be encoded into a single packed column.  To determine column indices
	// the column_indices property should be used instead.
	//
	// In Lance v1 these ids must be sorted but might not always be contiguous.
	Fields []int32 `protobuf:"varint,2,rep,packed,name=fields,proto3" json:"fields,omitempty"`
	// The top-level column indices for each field in the file.
	//
	// # If the data file is version 1 then this property will be empty
	//
	// Otherwise there must be one entry for each field in `fields`.
	//
	// Some fields may not correspond to a top-level column in the file.  In these cases
	// the index will -1.
	//
	// For example, consider the schema:
	//
	// - dimension: packed-struct (0):
	//   - x: u32 (1)
	//   - y: u32 (2)
	//
	// - path: `list<u32>` (3)
	// - embedding: `fsl<768>` (4)
	//   - fp64
	//
	// - borders: `fsl<4>` (5)
	//   - simple-struct (6)
	//   - margin: fp64 (7)
	//   - padding: fp64 (8)
	//
	// One possible column indices array could be:
	// [0, -1, -1, 1, 3, 4, 5, 6, 7]
	//
	// This reflects quite a few phenomenon:
	//   - The packed struct is encoded into a single column and there is no top-level column
	//     for the x or y fields
	//   - The variable sized list is encoded into two columns
	//   - The embedding is encoded into a single column (common for FSL of primitive) and there
	//     is not "FSL column"
	//   - The borders field actually does have an "FSL column"
	//
	// The column indices table may not have duplicates (other than -1)
	ColumnIndices []int32 `protobuf:"varint,3,rep,packed,name=column_indices,json=columnIndices,proto3" json:"column_indices,omitempty"`
	// The major file version used to create the file
	FileMajorVersion uint32 `protobuf:"varint,4,opt,name=file_major_version,json=fileMajorVersion,proto3" json:"file_major_version,omitempty"`
	// The minor file version used to create the file
	//
	// If both `file_major_version` and `file_minor_version` are set to 0,
	// then this is a version 0.1 or version 0.2 file.
	FileMinorVersion uint32 `protobuf:"varint,5,opt,name=file_minor_version,json=fileMinorVersion,proto3" json:"file_minor_version,omitempty"`
	// The known size of the file on disk in bytes.
	//
	// This is used to quickly find the footer of the file.
	//
	// When this is zero, it should be interpreted as "unknown".
	FileSizeBytes uint64 `protobuf:"varint,6,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	// The base path index of the data file. Used when the file is imported or referred from another dataset.
	// Lance use it as key of the base_paths field in Manifest to determine the actual base path of the data file.
	BaseId        *uint32 `protobuf:"varint,7,opt,name=base_id,json=baseId,proto3,oneof" json:"base_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFile) Reset() {
	*x = DataFile{}
	mi := &file_table_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFile) ProtoMessage() {}

func (x *DataFile) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFile.ProtoReflect.Descriptor instead.
func (*DataFile) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{7}
}

func (x *DataFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DataFile) GetFields() []int32 {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataFile) GetColumnIndices() []int32 {
	if x != nil {
		return x.ColumnIndices
	}
	return nil
}

func (x *DataFile) GetFileMajorVersion() uint32 {
	if x != nil {
		return x.FileMajorVersion
	}
	return 0
}

func (x *DataFile) GetFileMinorVersion() uint32 {
	if x != nil {
		return x.FileMinorVersion
	}
	return 0
}

func (x *DataFile) GetFileSizeBytes() uint64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *DataFile) GetBaseId() uint32 {
	if x != nil && x.BaseId != nil {
		return *x.BaseId
	}
	return 0
}

// Deletion File
//
// The path of the deletion file is constructed as:
//
//	{root}/_deletions/{fragment_id}-{read_version}-{id}.{extension}
//
// where {extension} depends on DeletionFileType.
type DeletionFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of deletion file.
	FileType DeletionFile_DeletionFileType `protobuf:"varint,1,opt,name=file_type,json=fileType,proto3,enum=lance.table.DeletionFile_DeletionFileType" json:"file_type,omitempty"`
	// The version of the dataset this deletion file was built from.
	ReadVersion uint64 `protobuf:"varint,2,opt,name=read_version,json=readVersion,proto3" json:"read_version,omitempty"`
	// An opaque id used to differentiate this file from others written by concurrent
	// writers.
	Id uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	// The number of rows that are marked as deleted.
	NumDeletedRows uint64 `protobuf:"varint,4,opt,name=num_deleted_rows,json=numDeletedRows,proto3" json:"num_deleted_rows,omitempty"`
	// The base path index of the deletion file. Used when the file is imported or referred from another
	// dataset. Lance uses it as key of the base_paths field in Manifest to determine the actual base
	// path of the deletion file.
	BaseId        *uint32 `protobuf:"varint,7,opt,name=base_id,json=baseId,proto3,oneof" json:"base_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletionFile) Reset() {
	*x = DeletionFile{}
	mi := &file_table_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletionFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionFile) ProtoMessage() {}

func (x *DeletionFile) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionFile.ProtoReflect.Descriptor instead.
func (*DeletionFile) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{8}
}

func (x *DeletionFile) GetFileType() DeletionFile_DeletionFileType {
	if x != nil {
		return x.FileType
	}
	return DeletionFile_ARROW_ARRAY
}

func (x *DeletionFile) GetReadVersion() uint64 {
	if x != nil {
		return x.ReadVersion
	}
	return 0
}

func (x *DeletionFile) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeletionFile) GetNumDeletedRows() uint64 {
	if x != nil {
		return x.NumDeletedRows
	}
	return 0
}

func (x *DeletionFile) GetBaseId() uint32 {
	if x != nil && x.BaseId != nil {
		return *x.BaseId
	}
	return 0
}

type ExternalFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the file, relative to the root of the table.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The byte offset in the file where the data starts.
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// The size of the data in the file, in bytes.
	Size          uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalFile) Reset() {
	*x = ExternalFile{}
	mi := &file_table_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalFile) ProtoMessage() {}

func (x *ExternalFile) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalFile.ProtoReflect.Descriptor instead.
func (*ExternalFile) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{9}
}

func (x *ExternalFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExternalFile) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ExternalFile) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Empty details messages for older indexes that don't take advantage of the details field.
type VectorIndexDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorIndexDetails) Reset() {
	*x = VectorIndexDetails{}
	mi := &file_table_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorIndexDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorIndexDetails) ProtoMessage() {}

func (x *VectorIndexDetails) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorIndexDetails.ProtoReflect.Descriptor instead.
func (*VectorIndexDetails) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{10}
}

type FragmentReuseIndexDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*FragmentReuseIndexDetails_Inline
	//	*FragmentReuseIndexDetails_External
	Content       isFragmentReuseIndexDetails_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FragmentReuseIndexDetails) Reset() {
	*x = FragmentReuseIndexDetails{}
	mi := &file_table_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentReuseIndexDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentReuseIndexDetails) ProtoMessage() {}

func (x *FragmentReuseIndexDetails) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentReuseIndexDetails.ProtoReflect.Descriptor instead.
func (*FragmentReuseIndexDetails) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{11}
}

func (x *FragmentReuseIndexDetails) GetContent() isFragmentReuseIndexDetails_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FragmentReuseIndexDetails) GetInline() *FragmentReuseIndexDetails_InlineContent {
	if x != nil {
		if x, ok := x.Content.(*FragmentReuseIndexDetails_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

func (x *FragmentReuseIndexDetails) GetExternal() *ExternalFile {
	if x != nil {
		if x, ok := x.Content.(*FragmentReuseIndexDetails_External); ok {
			return x.External
		}
	}
	return nil
}

type isFragmentReuseIndexDetails_Content interface {
	isFragmentReuseIndexDetails_Content()
}

type FragmentReuseIndexDetails_Inline struct {
	// if < 200KB, store the content inline, otherwise store the InlineContent bytes in external file
	Inline *FragmentReuseIndexDetails_InlineContent `protobuf:"bytes,1,opt,name=inline,proto3,oneof"`
}

type FragmentReuseIndexDetails_External struct {
	External *ExternalFile `protobuf:"bytes,2,opt,name=external,proto3,oneof"`
}

func (*FragmentReuseIndexDetails_Inline) isFragmentReuseIndexDetails_Content() {}

func (*FragmentReuseIndexDetails_External) isFragmentReuseIndexDetails_Content() {}

// Region manifest containing epoch-based fencing and WAL state.
// Each region has exactly one active writer at any time.
type RegionManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Region identifier (UUID v4).
	RegionId *UUID `protobuf:"bytes,11,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	// Manifest version number.
	// Matches the version encoded in the filename.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Region spec ID this region was created with.
	// Set at region creation and immutable thereafter.
	// A value of 0 indicates a manually-created region not governed by any spec.
	RegionSpecId uint32 `protobuf:"varint,10,opt,name=region_spec_id,json=regionSpecId,proto3" json:"region_spec_id,omitempty"`
	// Writer fencing token - monotonically increasing.
	// A writer must increment this when claiming the region.
	WriterEpoch uint64 `protobuf:"varint,2,opt,name=writer_epoch,json=writerEpoch,proto3" json:"writer_epoch,omitempty"`
	// The most recent WAL entry ID that has been flushed to a MemTable.
	// During recovery, replay starts from replay_after_wal_id + 1.
	ReplayAfterWalId uint64 `protobuf:"varint,3,opt,name=replay_after_wal_id,json=replayAfterWalId,proto3" json:"replay_after_wal_id,omitempty"`
	// The most recent WAL entry ID at the time manifest was updated.
	// This is a hint, not authoritative - recovery must list files to find actual state.
	WalIdLastSeen uint64 `protobuf:"varint,4,opt,name=wal_id_last_seen,json=walIdLastSeen,proto3" json:"wal_id_last_seen,omitempty"`
	// Next generation ID to create (incremented after each MemTable flush).
	CurrentGeneration uint64 `protobuf:"varint,6,opt,name=current_generation,json=currentGeneration,proto3" json:"current_generation,omitempty"`
	// List of flushed MemTable generations and their directory paths.
	FlushedGenerations []*FlushedGeneration `protobuf:"bytes,8,rep,name=flushed_generations,json=flushedGenerations,proto3" json:"flushed_generations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegionManifest) Reset() {
	*x = RegionManifest{}
	mi := &file_table_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionManifest) ProtoMessage() {}

func (x *RegionManifest) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionManifest.ProtoReflect.Descriptor instead.
func (*RegionManifest) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{12}
}

func (x *RegionManifest) GetRegionId() *UUID {
	if x != nil {
		return x.RegionId
	}
	return nil
}

func (x *RegionManifest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RegionManifest) GetRegionSpecId() uint32 {
	if x != nil {
		return x.RegionSpecId
	}
	return 0
}

func (x *RegionManifest) GetWriterEpoch() uint64 {
	if x != nil {
		return x.WriterEpoch
	}
	return 0
}

func (x *RegionManifest) GetReplayAfterWalId() uint64 {
	if x != nil {
		return x.ReplayAfterWalId
	}
	return 0
}

func (x *RegionManifest) GetWalIdLastSeen() uint64 {
	if x != nil {
		return x.WalIdLastSeen
	}
	return 0
}

func (x *RegionManifest) GetCurrentGeneration() uint64 {
	if x != nil {
		return x.CurrentGeneration
	}
	return 0
}

func (x *RegionManifest) GetFlushedGenerations() []*FlushedGeneration {
	if x != nil {
		return x.FlushedGenerations
	}
	return nil
}

// A flushed MemTable generation and its storage location.
type FlushedGeneration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generation number.
	Generation uint64 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// Directory name relative to the region directory.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushedGeneration) Reset() {
	*x = FlushedGeneration{}
	mi := &file_table_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushedGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushedGeneration) ProtoMessage() {}

func (x *FlushedGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushedGeneration.ProtoReflect.Descriptor instead.
func (*FlushedGeneration) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{13}
}

func (x *FlushedGeneration) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *FlushedGeneration) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// A region's merged generation, used in MemWalIndexDetails.
type MergedGeneration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Region identifier (UUID v4).
	RegionId *UUID `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	// Last generation merged to base table for this region.
	Generation    uint64 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergedGeneration) Reset() {
	*x = MergedGeneration{}
	mi := &file_table_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergedGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergedGeneration) ProtoMessage() {}

func (x *MergedGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergedGeneration.ProtoReflect.Descriptor instead.
func (*MergedGeneration) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{14}
}

func (x *MergedGeneration) GetRegionId() *UUID {
	if x != nil {
		return x.RegionId
	}
	return nil
}

func (x *MergedGeneration) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// Tracks which merged generation a base table index has been rebuilt to cover.
// Used to determine whether to read from flushed MemTable indexes or base table.
type IndexCatchupProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the base table index (must match an entry in maintained_indexes).
	IndexName string `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	// Per-region progress: the generation up to which this index covers.
	// If a region is not present, the index is assumed to be fully caught up
	// (i.e., caught_up_generation >= merged_generation for that region).
	CaughtUpGenerations []*MergedGeneration `protobuf:"bytes,2,rep,name=caught_up_generations,json=caughtUpGenerations,proto3" json:"caught_up_generations,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IndexCatchupProgress) Reset() {
	*x = IndexCatchupProgress{}
	mi := &file_table_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexCatchupProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexCatchupProgress) ProtoMessage() {}

func (x *IndexCatchupProgress) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexCatchupProgress.ProtoReflect.Descriptor instead.
func (*IndexCatchupProgress) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{15}
}

func (x *IndexCatchupProgress) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *IndexCatchupProgress) GetCaughtUpGenerations() []*MergedGeneration {
	if x != nil {
		return x.CaughtUpGenerations
	}
	return nil
}

// Index details for MemWAL Index, stored in IndexMetadata.index_details.
// This is the centralized structure for all MemWAL metadata:
// - Configuration (region specs, indexes to maintain)
// - Merge progress (merged generations per region)
// - Region state snapshots
//
// Writers read this index to get configuration before writing.
// Readers read this index to discover regions and their state.
// A background process updates the index periodically to keep region snapshots current.
//
// Region snapshots are stored as a Lance file with one row per region.
// The schema has one column per RegionManifest field, with region fields as columns:
//
//	region_id: fixed_size_binary(16)  -- UUID bytes
//	version: uint64
//	region_spec_id: uint32
//	writer_epoch: uint64
//	replay_after_wal_id: uint64
//	wal_id_last_seen: uint64
//	current_generation: uint64
//	merged_generation: uint64
//	flushed_generations: list<struct<generation: uint64, path: string>>
type MemWalIndexDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot timestamp (Unix timestamp in milliseconds).
	SnapshotTsMillis int64 `protobuf:"varint,1,opt,name=snapshot_ts_millis,json=snapshotTsMillis,proto3" json:"snapshot_ts_millis,omitempty"`
	// Number of regions in the snapshot.
	// Used to determine storage format without reading the snapshot data.
	NumRegions uint32 `protobuf:"varint,2,opt,name=num_regions,json=numRegions,proto3" json:"num_regions,omitempty"`
	// Inline region snapshots for small region counts.
	// When num_regions <= threshold (implementation-defined, e.g., 100),
	// snapshots are stored inline as serialized bytes.
	// Format: Lance file bytes with the region snapshot schema.
	InlineSnapshots []byte `protobuf:"bytes,3,opt,name=inline_snapshots,json=inlineSnapshots,proto3,oneof" json:"inline_snapshots,omitempty"`
	// Region specs defining how to derive region identifiers.
	// This configuration determines how rows are partitioned into regions.
	RegionSpecs []*RegionSpec `protobuf:"bytes,7,rep,name=region_specs,json=regionSpecs,proto3" json:"region_specs,omitempty"`
	// Indexes from the base table to maintain in MemTables.
	// These are index names referencing indexes defined on the base table.
	// The primary key btree index is always maintained implicitly and
	// should not be listed here.
	//
	// For vector indexes, MemTables inherit quantization parameters (PQ codebook,
	// SQ params) from the base table index to ensure distance comparability.
	MaintainedIndexes []string `protobuf:"bytes,8,rep,name=maintained_indexes,json=maintainedIndexes,proto3" json:"maintained_indexes,omitempty"`
	// Last generation merged to base table for each region.
	// This is updated atomically with merge-insert data commits, enabling
	// conflict resolution when multiple mergers operate concurrently.
	//
	// Note: This is separate from region snapshots because:
	// 1. merged_generations is updated by mergers (atomic with data commit)
	// 2. region snapshots are updated by background index builder
	MergedGenerations []*MergedGeneration `protobuf:"bytes,9,rep,name=merged_generations,json=mergedGenerations,proto3" json:"merged_generations,omitempty"`
	// Per-index catchup progress tracking.
	// When data is merged to the base table, base table indexes are rebuilt
	// asynchronously. This field tracks which generation each index covers.
	//
	// For indexed queries, if an index's caught_up_generation < merged_generation,
	// readers should use flushed MemTable indexes for the gap instead of
	// scanning unindexed data in the base table.
	//
	// If an index is not present in this list, it is assumed to be fully caught up.
	IndexCatchup  []*IndexCatchupProgress `protobuf:"bytes,10,rep,name=index_catchup,json=indexCatchup,proto3" json:"index_catchup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemWalIndexDetails) Reset() {
	*x = MemWalIndexDetails{}
	mi := &file_table_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemWalIndexDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemWalIndexDetails) ProtoMessage() {}

func (x *MemWalIndexDetails) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemWalIndexDetails.ProtoReflect.Descriptor instead.
func (*MemWalIndexDetails) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{16}
}

func (x *MemWalIndexDetails) GetSnapshotTsMillis() int64 {
	if x != nil {
		return x.SnapshotTsMillis
	}
	return 0
}

func (x *MemWalIndexDetails) GetNumRegions() uint32 {
	if x != nil {
		return x.NumRegions
	}
	return 0
}

func (x *MemWalIndexDetails) GetInlineSnapshots() []byte {
	if x != nil {
		return x.InlineSnapshots
	}
	return nil
}

func (x *MemWalIndexDetails) GetRegionSpecs() []*RegionSpec {
	if x != nil {
		return x.RegionSpecs
	}
	return nil
}

func (x *MemWalIndexDetails) GetMaintainedIndexes() []string {
	if x != nil {
		return x.MaintainedIndexes
	}
	return nil
}

func (x *MemWalIndexDetails) GetMergedGenerations() []*MergedGeneration {
	if x != nil {
		return x.MergedGenerations
	}
	return nil
}

func (x *MemWalIndexDetails) GetIndexCatchup() []*IndexCatchupProgress {
	if x != nil {
		return x.IndexCatchup
	}
	return nil
}

// Region spec definition.
type RegionSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this spec within the index.
	// IDs are never reused.
	SpecId uint32 `protobuf:"varint,1,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	// Region field definitions that determine how to compute region identifiers.
	Fields        []*RegionField `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionSpec) Reset() {
	*x = RegionSpec{}
	mi := &file_table_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSpec) ProtoMessage() {}

func (x *RegionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSpec.ProtoReflect.Descriptor instead.
func (*RegionSpec) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{17}
}

func (x *RegionSpec) GetSpecId() uint32 {
	if x != nil {
		return x.SpecId
	}
	return 0
}

func (x *RegionSpec) GetFields() []*RegionField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Region field definition.
type RegionField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique string identifier for this region field.
	FieldId string `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	// Field IDs referencing source columns in the schema.
	SourceIds []int32 `protobuf:"varint,2,rep,packed,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	// Well-known region transform name (e.g., "identity", "year", "bucket").
	// Mutually exclusive with expression.
	Transform *string `protobuf:"bytes,3,opt,name=transform,proto3,oneof" json:"transform,omitempty"`
	// DataFusion SQL expression for custom logic.
	// Mutually exclusive with transform.
	Expression *string `protobuf:"bytes,4,opt,name=expression,proto3,oneof" json:"expression,omitempty"`
	// Output type of the region value (Arrow type name).
	ResultType string `protobuf:"bytes,5,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	// Transform parameters (e.g., num_buckets for bucket transform).
	Parameters    map[string]string `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionField) Reset() {
	*x = RegionField{}
	mi := &file_table_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionField) ProtoMessage() {}

func (x *RegionField) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionField.ProtoReflect.Descriptor instead.
func (*RegionField) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{18}
}

func (x *RegionField) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *RegionField) GetSourceIds() []int32 {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *RegionField) GetTransform() string {
	if x != nil && x.Transform != nil {
		return *x.Transform
	}
	return ""
}

func (x *RegionField) GetExpression() string {
	if x != nil && x.Expression != nil {
		return *x.Expression
	}
	return ""
}

func (x *RegionField) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *RegionField) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Manifest_WriterVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the library that created this file.
	Library string `protobuf:"bytes,1,opt,name=library,proto3" json:"library,omitempty"`
	// The version of the library that created this file. Because we cannot assume
	// that the library is semantically versioned, this is a string. However, if it
	// is semantically versioned, it should be a valid semver string without any 'v'
	// prefix. For example: `2.0.0`, `2.0.0-rc.1`.
	//
	// For forward compatibility with older readers, when writing new manifests this
	// field should contain only the core version (major.minor.patch) without any
	// prerelease or build metadata. The prerelease/build info should be stored in
	// the separate prerelease and build_metadata fields instead.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Optional semver prerelease identifier.
	//
	// This field stores the prerelease portion of a semantic version separately
	// from the core version number. For example, if the full version is "2.0.0-rc.1",
	// the version field would contain "2.0.0" and prerelease would contain "rc.1".
	//
	// This separation ensures forward compatibility: older readers can parse the
	// clean version field without errors, while newer readers can reconstruct the
	// full semantic version by combining version, prerelease, and build_metadata.
	//
	// If absent, the version field is used as-is.
	Prerelease *string `protobuf:"bytes,3,opt,name=prerelease,proto3,oneof" json:"prerelease,omitempty"`
	// Optional semver build metadata.
	//
	// This field stores the build metadata portion of a semantic version separately
	// from the core version number. For example, if the full version is
	// "2.0.0-rc.1+build.123", the version field would contain "2.0.0", prerelease
	// would contain "rc.1", and build_metadata would contain "build.123".
	//
	// If absent, no build metadata is present.
	BuildMetadata *string `protobuf:"bytes,4,opt,name=build_metadata,json=buildMetadata,proto3,oneof" json:"build_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest_WriterVersion) Reset() {
	*x = Manifest_WriterVersion{}
	mi := &file_table_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest_WriterVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest_WriterVersion) ProtoMessage() {}

func (x *Manifest_WriterVersion) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest_WriterVersion.ProtoReflect.Descriptor instead.
func (*Manifest_WriterVersion) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Manifest_WriterVersion) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *Manifest_WriterVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest_WriterVersion) GetPrerelease() string {
	if x != nil && x.Prerelease != nil {
		return *x.Prerelease
	}
	return ""
}

func (x *Manifest_WriterVersion) GetBuildMetadata() string {
	if x != nil && x.BuildMetadata != nil {
		return *x.BuildMetadata
	}
	return ""
}

type Manifest_DataStorageFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The format of the data files (e.g. "lance")
	FileFormat string `protobuf:"bytes,1,opt,name=file_format,json=fileFormat,proto3" json:"file_format,omitempty"`
	// The max format version of the data files. The format of the version can vary by
	// file_format and is not required to follow semver.
	//
	// Every file in this version of the dataset has the same file_format version.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest_DataStorageFormat) Reset() {
	*x = Manifest_DataStorageFormat{}
	mi := &file_table_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest_DataStorageFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest_DataStorageFormat) ProtoMessage() {}

func (x *Manifest_DataStorageFormat) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest_DataStorageFormat.ProtoReflect.Descriptor instead.
func (*Manifest_DataStorageFormat) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Manifest_DataStorageFormat) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

func (x *Manifest_DataStorageFormat) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type FragmentReuseIndexDetails_InlineContent struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Versions      []*FragmentReuseIndexDetails_Version `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FragmentReuseIndexDetails_InlineContent) Reset() {
	*x = FragmentReuseIndexDetails_InlineContent{}
	mi := &file_table_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentReuseIndexDetails_InlineContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentReuseIndexDetails_InlineContent) ProtoMessage() {}

func (x *FragmentReuseIndexDetails_InlineContent) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentReuseIndexDetails_InlineContent.ProtoReflect.Descriptor instead.
func (*FragmentReuseIndexDetails_InlineContent) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{11, 0}
}

func (x *FragmentReuseIndexDetails_InlineContent) GetVersions() []*FragmentReuseIndexDetails_Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

type FragmentReuseIndexDetails_FragmentDigest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PhysicalRows   uint64                 `protobuf:"varint,2,opt,name=physical_rows,json=physicalRows,proto3" json:"physical_rows,omitempty"`
	NumDeletedRows uint64                 `protobuf:"varint,3,opt,name=num_deleted_rows,json=numDeletedRows,proto3" json:"num_deleted_rows,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FragmentReuseIndexDetails_FragmentDigest) Reset() {
	*x = FragmentReuseIndexDetails_FragmentDigest{}
	mi := &file_table_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentReuseIndexDetails_FragmentDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentReuseIndexDetails_FragmentDigest) ProtoMessage() {}

func (x *FragmentReuseIndexDetails_FragmentDigest) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentReuseIndexDetails_FragmentDigest.ProtoReflect.Descriptor instead.
func (*FragmentReuseIndexDetails_FragmentDigest) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{11, 1}
}

func (x *FragmentReuseIndexDetails_FragmentDigest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FragmentReuseIndexDetails_FragmentDigest) GetPhysicalRows() uint64 {
	if x != nil {
		return x.PhysicalRows
	}
	return 0
}

func (x *FragmentReuseIndexDetails_FragmentDigest) GetNumDeletedRows() uint64 {
	if x != nil {
		return x.NumDeletedRows
	}
	return 0
}

// A summarized version of the RewriteGroup information in a Rewrite transaction
type FragmentReuseIndexDetails_Group struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A roaring treemap of the changed row addresses.
	// When combined with the old fragment IDs and new fragment IDs,
	// it can recover the full mapping of old row addresses to either new row addresses or deleted.
	// this mapping can then be used to remap indexes or satisfy index queries for the new unindexed fragments.
	ChangedRowAddrs []byte                                      `protobuf:"bytes,1,opt,name=changed_row_addrs,json=changedRowAddrs,proto3" json:"changed_row_addrs,omitempty"`
	OldFragments    []*FragmentReuseIndexDetails_FragmentDigest `protobuf:"bytes,2,rep,name=old_fragments,json=oldFragments,proto3" json:"old_fragments,omitempty"`
	NewFragments    []*FragmentReuseIndexDetails_FragmentDigest `protobuf:"bytes,3,rep,name=new_fragments,json=newFragments,proto3" json:"new_fragments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FragmentReuseIndexDetails_Group) Reset() {
	*x = FragmentReuseIndexDetails_Group{}
	mi := &file_table_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentReuseIndexDetails_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentReuseIndexDetails_Group) ProtoMessage() {}

func (x *FragmentReuseIndexDetails_Group) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentReuseIndexDetails_Group.ProtoReflect.Descriptor instead.
func (*FragmentReuseIndexDetails_Group) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{11, 2}
}

func (x *FragmentReuseIndexDetails_Group) GetChangedRowAddrs() []byte {
	if x != nil {
		return x.ChangedRowAddrs
	}
	return nil
}

func (x *FragmentReuseIndexDetails_Group) GetOldFragments() []*FragmentReuseIndexDetails_FragmentDigest {
	if x != nil {
		return x.OldFragments
	}
	return nil
}

func (x *FragmentReuseIndexDetails_Group) GetNewFragments() []*FragmentReuseIndexDetails_FragmentDigest {
	if x != nil {
		return x.NewFragments
	}
	return nil
}

type FragmentReuseIndexDetails_Version struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dataset_version at the time the index adds this version entry
	DatasetVersion uint64                             `protobuf:"varint,1,opt,name=dataset_version,json=datasetVersion,proto3" json:"dataset_version,omitempty"`
	Groups         []*FragmentReuseIndexDetails_Group `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FragmentReuseIndexDetails_Version) Reset() {
	*x = FragmentReuseIndexDetails_Version{}
	mi := &file_table_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentReuseIndexDetails_Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentReuseIndexDetails_Version) ProtoMessage() {}

func (x *FragmentReuseIndexDetails_Version) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentReuseIndexDetails_Version.ProtoReflect.Descriptor instead.
func (*FragmentReuseIndexDetails_Version) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{11, 3}
}

func (x *FragmentReuseIndexDetails_Version) GetDatasetVersion() uint64 {
	if x != nil {
		return x.DatasetVersion
	}
	return 0
}

func (x *FragmentReuseIndexDetails_Version) GetGroups() []*FragmentReuseIndexDetails_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_table_proto protoreflect.FileDescriptor

const file_table_proto_rawDesc = "" +
	"\n" +
	"\vtable.proto\x12\vlance.table\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"file.proto\"\x1a\n" +
	"\x04UUID\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"\xb1\f\n" +
	"\bManifest\x12)\n" +
	"\x06fields\x18\x01 \x03(\v2\x11.lance.file.FieldR\x06fields\x12R\n" +
	"\x0fschema_metadata\x18\x05 \x03(\v2).lance.table.Manifest.SchemaMetadataEntryR\x0eschemaMetadata\x127\n" +
	"\tfragments\x18\x02 \x03(\v2\x19.lance.table.DataFragmentR\tfragments\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12(\n" +
	"\x10version_aux_data\x18\x04 \x01(\x04R\x0eversionAuxData\x12J\n" +
	"\x0ewriter_version\x18\r \x01(\v2#.lance.table.Manifest.WriterVersionR\rwriterVersion\x12(\n" +
	"\rindex_section\x18\x06 \x01(\x04H\x00R\findexSection\x88\x01\x01\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03tag\x18\b \x01(\tR\x03tag\x120\n" +
	"\x14reader_feature_flags\x18\t \x01(\x04R\x12readerFeatureFlags\x120\n" +
	"\x14writer_feature_flags\x18\n" +
	" \x01(\x04R\x12writerFeatureFlags\x12+\n" +
	"\x0fmax_fragment_id\x18\v \x01(\rH\x01R\rmaxFragmentId\x88\x01\x01\x12)\n" +
	"\x10transaction_file\x18\f \x01(\tR\x0ftransactionFile\x124\n" +
	"\x13transaction_section\x18\x15 \x01(\x04H\x02R\x12transactionSection\x88\x01\x01\x12\x1e\n" +
	"\vnext_row_id\x18\x0e \x01(\x04R\tnextRowId\x12H\n" +
	"\vdata_format\x18\x0f \x01(\v2'.lance.table.Manifest.DataStorageFormatR\n" +
	"dataFormat\x129\n" +
	"\x06config\x18\x10 \x03(\v2!.lance.table.Manifest.ConfigEntryR\x06config\x12O\n" +
	"\x0etable_metadata\x18\x13 \x03(\v2(.lance.table.Manifest.TableMetadataEntryR\rtableMetadata\x124\n" +
	"\n" +
	"base_paths\x18\x12 \x03(\v2\x15.lance.table.BasePathR\tbasePaths\x12\x1b\n" +
	"\x06branch\x18\x14 \x01(\tH\x03R\x06branch\x88\x01\x01\x1aA\n" +
	"\x13SchemaMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a\xb6\x01\n" +
	"\rWriterVersion\x12\x18\n" +
	"\alibrary\x18\x01 \x01(\tR\alibrary\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12#\n" +
	"\n" +
	"prerelease\x18\x03 \x01(\tH\x00R\n" +
	"prerelease\x88\x01\x01\x12*\n" +
	"\x0ebuild_metadata\x18\x04 \x01(\tH\x01R\rbuildMetadata\x88\x01\x01B\r\n" +
	"\v_prereleaseB\x11\n" +
	"\x0f_build_metadata\x1aN\n" +
	"\x11DataStorageFormat\x12\x1f\n" +
	"\vfile_format\x18\x01 \x01(\tR\n" +
	"fileFormat\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12TableMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_index_sectionB\x12\n" +
	"\x10_max_fragment_idB\x16\n" +
	"\x14_transaction_sectionB\t\n" +
	"\a_branchJ\x04\b\x11\x10\x12R\x14blob_dataset_version\"x\n" +
	"\bBasePath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12&\n" +
	"\x0fis_dataset_root\x18\x03 \x01(\bR\risDatasetRoot\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04pathB\a\n" +
	"\x05_name\"\x94\x01\n" +
	"\x0eVersionAuxData\x12E\n" +
	"\bmetadata\x18\x03 \x03(\v2).lance.table.VersionAuxData.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x88\x03\n" +
	"\rIndexMetadata\x12%\n" +
	"\x04uuid\x18\x01 \x01(\v2\x11.lance.table.UUIDR\x04uuid\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\x05R\x06fields\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\x0fdataset_version\x18\x04 \x01(\x04R\x0edatasetVersion\x12'\n" +
	"\x0ffragment_bitmap\x18\x05 \x01(\fR\x0efragmentBitmap\x129\n" +
	"\rindex_details\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\findexDetails\x12(\n" +
	"\rindex_version\x18\a \x01(\x05H\x00R\findexVersion\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\b \x01(\x04H\x01R\tcreatedAt\x88\x01\x01\x12\x1c\n" +
	"\abase_id\x18\t \x01(\rH\x02R\x06baseId\x88\x01\x01B\x10\n" +
	"\x0e_index_versionB\r\n" +
	"\v_created_atB\n" +
	"\n" +
	"\b_base_id\"D\n" +
	"\fIndexSection\x124\n" +
	"\aindices\x18\x01 \x03(\v2\x1a.lance.table.IndexMetadataR\aindices\"\xc1\x05\n" +
	"\fDataFragment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12+\n" +
	"\x05files\x18\x02 \x03(\v2\x15.lance.table.DataFileR\x05files\x12>\n" +
	"\rdeletion_file\x18\x03 \x01(\v2\x19.lance.table.DeletionFileR\fdeletionFile\x12&\n" +
	"\x0einline_row_ids\x18\x05 \x01(\fH\x00R\finlineRowIds\x12E\n" +
	"\x10external_row_ids\x18\x06 \x01(\v2\x19.lance.table.ExternalFileH\x00R\x0eexternalRowIds\x12F\n" +
	"\x1finline_last_updated_at_versions\x18\a \x01(\fH\x01R\x1binlineLastUpdatedAtVersions\x12e\n" +
	"!external_last_updated_at_versions\x18\b \x01(\v2\x19.lance.table.ExternalFileH\x01R\x1dexternalLastUpdatedAtVersions\x12=\n" +
	"\x1ainline_created_at_versions\x18\t \x01(\fH\x02R\x17inlineCreatedAtVersions\x12\\\n" +
	"\x1cexternal_created_at_versions\x18\n" +
	" \x01(\v2\x19.lance.table.ExternalFileH\x02R\x19externalCreatedAtVersions\x12#\n" +
	"\rphysical_rows\x18\x04 \x01(\x04R\fphysicalRowsB\x11\n" +
	"\x0frow_id_sequenceB\"\n" +
	" last_updated_at_version_sequenceB\x1d\n" +
	"\x1bcreated_at_version_sequence\"\x8b\x02\n" +
	"\bDataFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\x05R\x06fields\x12%\n" +
	"\x0ecolumn_indices\x18\x03 \x03(\x05R\rcolumnIndices\x12,\n" +
	"\x12file_major_version\x18\x04 \x01(\rR\x10fileMajorVersion\x12,\n" +
	"\x12file_minor_version\x18\x05 \x01(\rR\x10fileMinorVersion\x12&\n" +
	"\x0ffile_size_bytes\x18\x06 \x01(\x04R\rfileSizeBytes\x12\x1c\n" +
	"\abase_id\x18\a \x01(\rH\x00R\x06baseId\x88\x01\x01B\n" +
	"\n" +
	"\b_base_id\"\x8f\x02\n" +
	"\fDeletionFile\x12G\n" +
	"\tfile_type\x18\x01 \x01(\x0e2*.lance.table.DeletionFile.DeletionFileTypeR\bfileType\x12!\n" +
	"\fread_version\x18\x02 \x01(\x04R\vreadVersion\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\x12(\n" +
	"\x10num_deleted_rows\x18\x04 \x01(\x04R\x0enumDeletedRows\x12\x1c\n" +
	"\abase_id\x18\a \x01(\rH\x00R\x06baseId\x88\x01\x01\"/\n" +
	"\x10DeletionFileType\x12\x0f\n" +
	"\vARROW_ARRAY\x10\x00\x12\n" +
	"\n" +
	"\x06BITMAP\x10\x01B\n" +
	"\n" +
	"\b_base_id\"N\n" +
	"\fExternalFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"\x14\n" +
	"\x12VectorIndexDetails\"\xe5\x05\n" +
	"\x19FragmentReuseIndexDetails\x12N\n" +
	"\x06inline\x18\x01 \x01(\v24.lance.table.FragmentReuseIndexDetails.InlineContentH\x00R\x06inline\x127\n" +
	"\bexternal\x18\x02 \x01(\v2\x19.lance.table.ExternalFileH\x00R\bexternal\x1a[\n" +
	"\rInlineContent\x12J\n" +
	"\bversions\x18\x01 \x03(\v2..lance.table.FragmentReuseIndexDetails.VersionR\bversions\x1ao\n" +
	"\x0eFragmentDigest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rphysical_rows\x18\x02 \x01(\x04R\fphysicalRows\x12(\n" +
	"\x10num_deleted_rows\x18\x03 \x01(\x04R\x0enumDeletedRows\x1a\xeb\x01\n" +
	"\x05Group\x12*\n" +
	"\x11changed_row_addrs\x18\x01 \x01(\fR\x0fchangedRowAddrs\x12Z\n" +
	"\rold_fragments\x18\x02 \x03(\v25.lance.table.FragmentReuseIndexDetails.FragmentDigestR\foldFragments\x12Z\n" +
	"\rnew_fragments\x18\x03 \x03(\v25.lance.table.FragmentReuseIndexDetails.FragmentDigestR\fnewFragments\x1ax\n" +
	"\aVersion\x12'\n" +
	"\x0fdataset_version\x18\x01 \x01(\x04R\x0edatasetVersion\x12D\n" +
	"\x06groups\x18\x03 \x03(\v2,.lance.table.FragmentReuseIndexDetails.GroupR\x06groupsB\t\n" +
	"\acontent\"\xfb\x02\n" +
	"\x0eRegionManifest\x12.\n" +
	"\tregion_id\x18\v \x01(\v2\x11.lance.table.UUIDR\bregionId\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12$\n" +
	"\x0eregion_spec_id\x18\n" +
	" \x01(\rR\fregionSpecId\x12!\n" +
	"\fwriter_epoch\x18\x02 \x01(\x04R\vwriterEpoch\x12-\n" +
	"\x13replay_after_wal_id\x18\x03 \x01(\x04R\x10replayAfterWalId\x12'\n" +
	"\x10wal_id_last_seen\x18\x04 \x01(\x04R\rwalIdLastSeen\x12-\n" +
	"\x12current_generation\x18\x06 \x01(\x04R\x11currentGeneration\x12O\n" +
	"\x13flushed_generations\x18\b \x03(\v2\x1e.lance.table.FlushedGenerationR\x12flushedGenerations\"G\n" +
	"\x11FlushedGeneration\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"b\n" +
	"\x10MergedGeneration\x12.\n" +
	"\tregion_id\x18\x01 \x01(\v2\x11.lance.table.UUIDR\bregionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\"\x88\x01\n" +
	"\x14IndexCatchupProgress\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12Q\n" +
	"\x15caught_up_generations\x18\x02 \x03(\v2\x1d.lance.table.MergedGenerationR\x13caughtUpGenerations\"\xa9\x03\n" +
	"\x12MemWalIndexDetails\x12,\n" +
	"\x12snapshot_ts_millis\x18\x01 \x01(\x03R\x10snapshotTsMillis\x12\x1f\n" +
	"\vnum_regions\x18\x02 \x01(\rR\n" +
	"numRegions\x12.\n" +
	"\x10inline_snapshots\x18\x03 \x01(\fH\x00R\x0finlineSnapshots\x88\x01\x01\x12:\n" +
	"\fregion_specs\x18\a \x03(\v2\x17.lance.table.RegionSpecR\vregionSpecs\x12-\n" +
	"\x12maintained_indexes\x18\b \x03(\tR\x11maintainedIndexes\x12L\n" +
	"\x12merged_generations\x18\t \x03(\v2\x1d.lance.table.MergedGenerationR\x11mergedGenerations\x12F\n" +
	"\rindex_catchup\x18\n" +
	" \x03(\v2!.lance.table.IndexCatchupProgressR\findexCatchupB\x13\n" +
	"\x11_inline_snapshots\"W\n" +
	"\n" +
	"RegionSpec\x12\x17\n" +
	"\aspec_id\x18\x01 \x01(\rR\x06specId\x120\n" +
	"\x06fields\x18\x02 \x03(\v2\x18.lance.table.RegionFieldR\x06fields\"\xd6\x02\n" +
	"\vRegionField\x12\x19\n" +
	"\bfield_id\x18\x01 \x01(\tR\afieldId\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x02 \x03(\x05R\tsourceIds\x12!\n" +
	"\ttransform\x18\x03 \x01(\tH\x00R\ttransform\x88\x01\x01\x12#\n" +
	"\n" +
	"expression\x18\x04 \x01(\tH\x01R\n" +
	"expression\x88\x01\x01\x12\x1f\n" +
	"\vresult_type\x18\x05 \x01(\tR\n" +
	"resultType\x12H\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v2(.lance.table.RegionField.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_transformB\r\n" +
	"\v_expressionB9Z7github.com/daviszhen/plan/pkg/storage2/proto;storage2pbb\x06proto3"

var (
	file_table_proto_rawDescOnce sync.Once
	file_table_proto_rawDescData []byte
)

func file_table_proto_rawDescGZIP() []byte {
	file_table_proto_rawDescOnce.Do(func() {
		file_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_table_proto_rawDesc), len(file_table_proto_rawDesc)))
	})
	return file_table_proto_rawDescData
}

var file_table_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_table_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_table_proto_goTypes = []any{
	(DeletionFile_DeletionFileType)(0), // 0: lance.table.DeletionFile.DeletionFileType
	(*UUID)(nil),                       // 1: lance.table.UUID
	(*Manifest)(nil),                   // 2: lance.table.Manifest
	(*BasePath)(nil),                   // 3: lance.table.BasePath
	(*VersionAuxData)(nil),             // 4: lance.table.VersionAuxData
	(*IndexMetadata)(nil),              // 5: lance.table.IndexMetadata
	(*IndexSection)(nil),               // 6: lance.table.IndexSection
	(*DataFragment)(nil),               // 7: lance.table.DataFragment
	(*DataFile)(nil),                   // 8: lance.table.DataFile
	(*DeletionFile)(nil),               // 9: lance.table.DeletionFile
	(*ExternalFile)(nil),               // 10: lance.table.ExternalFile
	(*VectorIndexDetails)(nil),         // 11: lance.table.VectorIndexDetails
	(*FragmentReuseIndexDetails)(nil),  // 12: lance.table.FragmentReuseIndexDetails
	(*RegionManifest)(nil),             // 13: lance.table.RegionManifest
	(*FlushedGeneration)(nil),          // 14: lance.table.FlushedGeneration
	(*MergedGeneration)(nil),           // 15: lance.table.MergedGeneration
	(*IndexCatchupProgress)(nil),       // 16: lance.table.IndexCatchupProgress
	(*MemWalIndexDetails)(nil),         // 17: lance.table.MemWalIndexDetails
	(*RegionSpec)(nil),                 // 18: lance.table.RegionSpec
	(*RegionField)(nil),                // 19: lance.table.RegionField
	nil,                                // 20: lance.table.Manifest.SchemaMetadataEntry
	(*Manifest_WriterVersion)(nil),     // 21: lance.table.Manifest.WriterVersion
	(*Manifest_DataStorageFormat)(nil), // 22: lance.table.Manifest.DataStorageFormat
	nil,                                // 23: lance.table.Manifest.ConfigEntry
	nil,                                // 24: lance.table.Manifest.TableMetadataEntry
	nil,                                // 25: lance.table.VersionAuxData.MetadataEntry
	(*FragmentReuseIndexDetails_InlineContent)(nil),  // 26: lance.table.FragmentReuseIndexDetails.InlineContent
	(*FragmentReuseIndexDetails_FragmentDigest)(nil), // 27: lance.table.FragmentReuseIndexDetails.FragmentDigest
	(*FragmentReuseIndexDetails_Group)(nil),          // 28: lance.table.FragmentReuseIndexDetails.Group
	(*FragmentReuseIndexDetails_Version)(nil),        // 29: lance.table.FragmentReuseIndexDetails.Version
	nil,                           // 30: lance.table.RegionField.ParametersEntry
	(*Field)(nil),                 // 31: lance.file.Field
	(*timestamppb.Timestamp)(nil), // 32: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 33: google.protobuf.Any
}
var file_table_proto_depIdxs = []int32{
	31, // 0: lance.table.Manifest.fields:type_name -> lance.file.Field
	20, // 1: lance.table.Manifest.schema_metadata:type_name -> lance.table.Manifest.SchemaMetadataEntry
	7,  // 2: lance.table.Manifest.fragments:type_name -> lance.table.DataFragment
	21, // 3: lance.table.Manifest.writer_version:type_name -> lance.table.Manifest.WriterVersion
	32, // 4: lance.table.Manifest.timestamp:type_name -> google.protobuf.Timestamp
	22, // 5: lance.table.Manifest.data_format:type_name -> lance.table.Manifest.DataStorageFormat
	23, // 6: lance.table.Manifest.config:type_name -> lance.table.Manifest.ConfigEntry
	24, // 7: lance.table.Manifest.table_metadata:type_name -> lance.table.Manifest.TableMetadataEntry
	3,  // 8: lance.table.Manifest.base_paths:type_name -> lance.table.BasePath
	25, // 9: lance.table.VersionAuxData.metadata:type_name -> lance.table.VersionAuxData.MetadataEntry
	1,  // 10: lance.table.IndexMetadata.uuid:type_name -> lance.table.UUID
	33, // 11: lance.table.IndexMetadata.index_details:type_name -> google.protobuf.Any
	5,  // 12: lance.table.IndexSection.indices:type_name -> lance.table.IndexMetadata
	8,  // 13: lance.table.DataFragment.files:type_name -> lance.table.DataFile
	9,  // 14: lance.table.DataFragment.deletion_file:type_name -> lance.table.DeletionFile
	10, // 15: lance.table.DataFragment.external_row_ids:type_name -> lance.table.ExternalFile
	10, // 16: lance.table.DataFragment.external_last_updated_at_versions:type_name -> lance.table.ExternalFile
	10, // 17: lance.table.DataFragment.external_created_at_versions:type_name -> lance.table.ExternalFile
	0,  // 18: lance.table.DeletionFile.file_type:type_name -> lance.table.DeletionFile.DeletionFileType
	26, // 19: lance.table.FragmentReuseIndexDetails.inline:type_name -> lance.table.FragmentReuseIndexDetails.InlineContent
	10, // 20: lance.table.FragmentReuseIndexDetails.external:type_name -> lance.table.ExternalFile
	1,  // 21: lance.table.RegionManifest.region_id:type_name -> lance.table.UUID
	14, // 22: lance.table.RegionManifest.flushed_generations:type_name -> lance.table.FlushedGeneration
	1,  // 23: lance.table.MergedGeneration.region_id:type_name -> lance.table.UUID
	15, // 24: lance.table.IndexCatchupProgress.caught_up_generations:type_name -> lance.table.MergedGeneration
	18, // 25: lance.table.MemWalIndexDetails.region_specs:type_name -> lance.table.RegionSpec
	15, // 26: lance.table.MemWalIndexDetails.merged_generations:type_name -> lance.table.MergedGeneration
	16, // 27: lance.table.MemWalIndexDetails.index_catchup:type_name -> lance.table.IndexCatchupProgress
	19, // 28: lance.table.RegionSpec.fields:type_name -> lance.table.RegionField
	30, // 29: lance.table.RegionField.parameters:type_name -> lance.table.RegionField.ParametersEntry
	29, // 30: lance.table.FragmentReuseIndexDetails.InlineContent.versions:type_name -> lance.table.FragmentReuseIndexDetails.Version
	27, // 31: lance.table.FragmentReuseIndexDetails.Group.old_fragments:type_name -> lance.table.FragmentReuseIndexDetails.FragmentDigest
	27, // 32: lance.table.FragmentReuseIndexDetails.Group.new_fragments:type_name -> lance.table.FragmentReuseIndexDetails.FragmentDigest
	28, // 33: lance.table.FragmentReuseIndexDetails.Version.groups:type_name -> lance.table.FragmentReuseIndexDetails.Group
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_table_proto_init() }
func file_table_proto_init() {
	if File_table_proto != nil {
		return
	}
	file_file_proto_init()
	file_table_proto_msgTypes[1].OneofWrappers = []any{}
	file_table_proto_msgTypes[2].OneofWrappers = []any{}
	file_table_proto_msgTypes[4].OneofWrappers = []any{}
	file_table_proto_msgTypes[6].OneofWrappers = []any{
		(*DataFragment_InlineRowIds)(nil),
		(*DataFragment_ExternalRowIds)(nil),
		(*DataFragment_InlineLastUpdatedAtVersions)(nil),
		(*DataFragment_ExternalLastUpdatedAtVersions)(nil),
		(*DataFragment_InlineCreatedAtVersions)(nil),
		(*DataFragment_ExternalCreatedAtVersions)(nil),
	}
	file_table_proto_msgTypes[7].OneofWrappers = []any{}
	file_table_proto_msgTypes[8].OneofWrappers = []any{}
	file_table_proto_msgTypes[11].OneofWrappers = []any{
		(*FragmentReuseIndexDetails_Inline)(nil),
		(*FragmentReuseIndexDetails_External)(nil),
	}
	file_table_proto_msgTypes[16].OneofWrappers = []any{}
	file_table_proto_msgTypes[18].OneofWrappers = []any{}
	file_table_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_table_proto_rawDesc), len(file_table_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_table_proto_goTypes,
		DependencyIndexes: file_table_proto_depIdxs,
		EnumInfos:         file_table_proto_enumTypes,
		MessageInfos:      file_table_proto_msgTypes,
	}.Build()
	File_table_proto = out.File
	file_table_proto_goTypes = nil
	file_table_proto_depIdxs = nil
}
