// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transaction.proto

package storage2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The mode of update operation
type Transaction_UpdateMode int32

const (
	// / rows are deleted in current fragments and rewritten in new fragments.
	// / This is most optimal when the majority of columns are being rewritten
	// / or only a few rows are being updated.
	Transaction_REWRITE_ROWS Transaction_UpdateMode = 0
	// / within each fragment, columns are fully rewritten and inserted as new data files.
	// / Old versions of columns are tombstoned. This is most optimal when most rows are affected
	// / but a small subset of columns are affected.
	Transaction_REWRITE_COLUMNS Transaction_UpdateMode = 1
)

// Enum value maps for Transaction_UpdateMode.
var (
	Transaction_UpdateMode_name = map[int32]string{
		0: "REWRITE_ROWS",
		1: "REWRITE_COLUMNS",
	}
	Transaction_UpdateMode_value = map[string]int32{
		"REWRITE_ROWS":    0,
		"REWRITE_COLUMNS": 1,
	}
)

func (x Transaction_UpdateMode) Enum() *Transaction_UpdateMode {
	p := new(Transaction_UpdateMode)
	*p = x
	return p
}

func (x Transaction_UpdateMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_UpdateMode) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[0].Descriptor()
}

func (Transaction_UpdateMode) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[0]
}

func (x Transaction_UpdateMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_UpdateMode.Descriptor instead.
func (Transaction_UpdateMode) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 0}
}

// A transaction represents the changes to a dataset.
//
// This has two purposes:
//  1. When retrying a commit, the transaction can be used to re-build an updated
//     manifest.
//  2. When there's a conflict, this can be used to determine whether the other
//     transaction is compatible with this one.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version of the dataset this transaction was built from.
	//
	// For example, for a delete transaction this means the version of the dataset
	// that was read from while evaluating the deletion predicate.
	ReadVersion uint64 `protobuf:"varint,1,opt,name=read_version,json=readVersion,proto3" json:"read_version,omitempty"`
	// The UUID that unique identifies a transaction.
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Optional version tag.
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	// Optional properties for the transaction
	// __lance_commit_message is a reserved key
	TransactionProperties map[string]string `protobuf:"bytes,4,rep,name=transaction_properties,json=transactionProperties,proto3" json:"transaction_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The operation of this transaction.
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*Transaction_Append_
	//	*Transaction_Delete_
	//	*Transaction_Overwrite_
	//	*Transaction_CreateIndex_
	//	*Transaction_Rewrite_
	//	*Transaction_Merge_
	//	*Transaction_Restore_
	//	*Transaction_ReserveFragments_
	//	*Transaction_Update_
	//	*Transaction_Project_
	//	*Transaction_UpdateConfig_
	//	*Transaction_DataReplacement_
	//	*Transaction_UpdateMemWalState_
	//	*Transaction_Clone_
	//	*Transaction_UpdateBases_
	Operation     isTransaction_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetReadVersion() uint64 {
	if x != nil {
		return x.ReadVersion
	}
	return 0
}

func (x *Transaction) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Transaction) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Transaction) GetTransactionProperties() map[string]string {
	if x != nil {
		return x.TransactionProperties
	}
	return nil
}

func (x *Transaction) GetOperation() isTransaction_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Transaction) GetAppend() *Transaction_Append {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_Append_); ok {
			return x.Append
		}
	}
	return nil
}

func (x *Transaction) GetDelete() *Transaction_Delete {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_Delete_); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Transaction) GetOverwrite() *Transaction_Overwrite {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_Overwrite_); ok {
			return x.Overwrite
		}
	}
	return nil
}

func (x *Transaction) GetCreateIndex() *Transaction_CreateIndex {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_CreateIndex_); ok {
			return x.CreateIndex
		}
	}
	return nil
}

func (x *Transaction) GetRewrite() *Transaction_Rewrite {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_Rewrite_); ok {
			return x.Rewrite
		}
	}
	return nil
}

func (x *Transaction) GetMerge() *Transaction_Merge {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_Merge_); ok {
			return x.Merge
		}
	}
	return nil
}

func (x *Transaction) GetRestore() *Transaction_Restore {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_Restore_); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *Transaction) GetReserveFragments() *Transaction_ReserveFragments {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_ReserveFragments_); ok {
			return x.ReserveFragments
		}
	}
	return nil
}

func (x *Transaction) GetUpdate() *Transaction_Update {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_Update_); ok {
			return x.Update
		}
	}
	return nil
}

func (x *Transaction) GetProject() *Transaction_Project {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_Project_); ok {
			return x.Project
		}
	}
	return nil
}

func (x *Transaction) GetUpdateConfig() *Transaction_UpdateConfig {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_UpdateConfig_); ok {
			return x.UpdateConfig
		}
	}
	return nil
}

func (x *Transaction) GetDataReplacement() *Transaction_DataReplacement {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_DataReplacement_); ok {
			return x.DataReplacement
		}
	}
	return nil
}

func (x *Transaction) GetUpdateMemWalState() *Transaction_UpdateMemWalState {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_UpdateMemWalState_); ok {
			return x.UpdateMemWalState
		}
	}
	return nil
}

func (x *Transaction) GetClone() *Transaction_Clone {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_Clone_); ok {
			return x.Clone
		}
	}
	return nil
}

func (x *Transaction) GetUpdateBases() *Transaction_UpdateBases {
	if x != nil {
		if x, ok := x.Operation.(*Transaction_UpdateBases_); ok {
			return x.UpdateBases
		}
	}
	return nil
}

type isTransaction_Operation interface {
	isTransaction_Operation()
}

type Transaction_Append_ struct {
	Append *Transaction_Append `protobuf:"bytes,100,opt,name=append,proto3,oneof"`
}

type Transaction_Delete_ struct {
	Delete *Transaction_Delete `protobuf:"bytes,101,opt,name=delete,proto3,oneof"`
}

type Transaction_Overwrite_ struct {
	Overwrite *Transaction_Overwrite `protobuf:"bytes,102,opt,name=overwrite,proto3,oneof"`
}

type Transaction_CreateIndex_ struct {
	CreateIndex *Transaction_CreateIndex `protobuf:"bytes,103,opt,name=create_index,json=createIndex,proto3,oneof"`
}

type Transaction_Rewrite_ struct {
	Rewrite *Transaction_Rewrite `protobuf:"bytes,104,opt,name=rewrite,proto3,oneof"`
}

type Transaction_Merge_ struct {
	Merge *Transaction_Merge `protobuf:"bytes,105,opt,name=merge,proto3,oneof"`
}

type Transaction_Restore_ struct {
	Restore *Transaction_Restore `protobuf:"bytes,106,opt,name=restore,proto3,oneof"`
}

type Transaction_ReserveFragments_ struct {
	ReserveFragments *Transaction_ReserveFragments `protobuf:"bytes,107,opt,name=reserve_fragments,json=reserveFragments,proto3,oneof"`
}

type Transaction_Update_ struct {
	Update *Transaction_Update `protobuf:"bytes,108,opt,name=update,proto3,oneof"`
}

type Transaction_Project_ struct {
	Project *Transaction_Project `protobuf:"bytes,109,opt,name=project,proto3,oneof"`
}

type Transaction_UpdateConfig_ struct {
	UpdateConfig *Transaction_UpdateConfig `protobuf:"bytes,110,opt,name=update_config,json=updateConfig,proto3,oneof"`
}

type Transaction_DataReplacement_ struct {
	DataReplacement *Transaction_DataReplacement `protobuf:"bytes,111,opt,name=data_replacement,json=dataReplacement,proto3,oneof"`
}

type Transaction_UpdateMemWalState_ struct {
	UpdateMemWalState *Transaction_UpdateMemWalState `protobuf:"bytes,112,opt,name=update_mem_wal_state,json=updateMemWalState,proto3,oneof"`
}

type Transaction_Clone_ struct {
	Clone *Transaction_Clone `protobuf:"bytes,113,opt,name=clone,proto3,oneof"`
}

type Transaction_UpdateBases_ struct {
	UpdateBases *Transaction_UpdateBases `protobuf:"bytes,114,opt,name=update_bases,json=updateBases,proto3,oneof"`
}

func (*Transaction_Append_) isTransaction_Operation() {}

func (*Transaction_Delete_) isTransaction_Operation() {}

func (*Transaction_Overwrite_) isTransaction_Operation() {}

func (*Transaction_CreateIndex_) isTransaction_Operation() {}

func (*Transaction_Rewrite_) isTransaction_Operation() {}

func (*Transaction_Merge_) isTransaction_Operation() {}

func (*Transaction_Restore_) isTransaction_Operation() {}

func (*Transaction_ReserveFragments_) isTransaction_Operation() {}

func (*Transaction_Update_) isTransaction_Operation() {}

func (*Transaction_Project_) isTransaction_Operation() {}

func (*Transaction_UpdateConfig_) isTransaction_Operation() {}

func (*Transaction_DataReplacement_) isTransaction_Operation() {}

func (*Transaction_UpdateMemWalState_) isTransaction_Operation() {}

func (*Transaction_Clone_) isTransaction_Operation() {}

func (*Transaction_UpdateBases_) isTransaction_Operation() {}

// Add new rows to the dataset.
type Transaction_Append struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new fragments to append.
	//
	// Fragment IDs are not yet assigned.
	Fragments     []*DataFragment `protobuf:"bytes,1,rep,name=fragments,proto3" json:"fragments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Append) Reset() {
	*x = Transaction_Append{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Append) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Append) ProtoMessage() {}

func (x *Transaction_Append) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Append.ProtoReflect.Descriptor instead.
func (*Transaction_Append) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Transaction_Append) GetFragments() []*DataFragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

// Mark rows as deleted.
type Transaction_Delete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fragments to update
	//
	// The fragment IDs will match existing fragments in the dataset.
	UpdatedFragments []*DataFragment `protobuf:"bytes,1,rep,name=updated_fragments,json=updatedFragments,proto3" json:"updated_fragments,omitempty"`
	// The fragments to delete entirely.
	DeletedFragmentIds []uint64 `protobuf:"varint,2,rep,packed,name=deleted_fragment_ids,json=deletedFragmentIds,proto3" json:"deleted_fragment_ids,omitempty"`
	// The predicate that was evaluated
	//
	// This may be used to determine whether the delete would have affected
	// files written by a concurrent transaction.
	Predicate     string `protobuf:"bytes,3,opt,name=predicate,proto3" json:"predicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Delete) Reset() {
	*x = Transaction_Delete{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Delete) ProtoMessage() {}

func (x *Transaction_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Delete.ProtoReflect.Descriptor instead.
func (*Transaction_Delete) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Transaction_Delete) GetUpdatedFragments() []*DataFragment {
	if x != nil {
		return x.UpdatedFragments
	}
	return nil
}

func (x *Transaction_Delete) GetDeletedFragmentIds() []uint64 {
	if x != nil {
		return x.DeletedFragmentIds
	}
	return nil
}

func (x *Transaction_Delete) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

// Create or overwrite the entire dataset.
type Transaction_Overwrite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new fragments
	//
	// Fragment IDs are not yet assigned.
	Fragments []*DataFragment `protobuf:"bytes,1,rep,name=fragments,proto3" json:"fragments,omitempty"`
	// The new schema
	Schema []*Field `protobuf:"bytes,2,rep,name=schema,proto3" json:"schema,omitempty"`
	// Schema metadata.
	SchemaMetadata map[string][]byte `protobuf:"bytes,3,rep,name=schema_metadata,json=schemaMetadata,proto3" json:"schema_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Key-value pairs to merge with existing config.
	ConfigUpsertValues map[string]string `protobuf:"bytes,4,rep,name=config_upsert_values,json=configUpsertValues,proto3" json:"config_upsert_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The base paths to be added for the initial dataset creation
	InitialBases  []*BasePath `protobuf:"bytes,5,rep,name=initial_bases,json=initialBases,proto3" json:"initial_bases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Overwrite) Reset() {
	*x = Transaction_Overwrite{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Overwrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Overwrite) ProtoMessage() {}

func (x *Transaction_Overwrite) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Overwrite.ProtoReflect.Descriptor instead.
func (*Transaction_Overwrite) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Transaction_Overwrite) GetFragments() []*DataFragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

func (x *Transaction_Overwrite) GetSchema() []*Field {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Transaction_Overwrite) GetSchemaMetadata() map[string][]byte {
	if x != nil {
		return x.SchemaMetadata
	}
	return nil
}

func (x *Transaction_Overwrite) GetConfigUpsertValues() map[string]string {
	if x != nil {
		return x.ConfigUpsertValues
	}
	return nil
}

func (x *Transaction_Overwrite) GetInitialBases() []*BasePath {
	if x != nil {
		return x.InitialBases
	}
	return nil
}

// Add or replace a new secondary index.
//
// This is also used to remove an index (we are replacing it with nothing)
//
// - new_indices: the modified indices, empty if dropping indices only
// - removed_indices: the indices that are being replaced
type Transaction_CreateIndex struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewIndices     []*IndexMetadata       `protobuf:"bytes,1,rep,name=new_indices,json=newIndices,proto3" json:"new_indices,omitempty"`
	RemovedIndices []*IndexMetadata       `protobuf:"bytes,2,rep,name=removed_indices,json=removedIndices,proto3" json:"removed_indices,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction_CreateIndex) Reset() {
	*x = Transaction_CreateIndex{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_CreateIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_CreateIndex) ProtoMessage() {}

func (x *Transaction_CreateIndex) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_CreateIndex.ProtoReflect.Descriptor instead.
func (*Transaction_CreateIndex) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Transaction_CreateIndex) GetNewIndices() []*IndexMetadata {
	if x != nil {
		return x.NewIndices
	}
	return nil
}

func (x *Transaction_CreateIndex) GetRemovedIndices() []*IndexMetadata {
	if x != nil {
		return x.RemovedIndices
	}
	return nil
}

// An operation that rewrites but does not change the data in the table. These
// kinds of operations just rearrange data.
type Transaction_Rewrite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The old fragments that are being replaced
	//
	// DEPRECATED: use groups instead.
	//
	// These should all have existing fragment IDs.
	OldFragments []*DataFragment `protobuf:"bytes,1,rep,name=old_fragments,json=oldFragments,proto3" json:"old_fragments,omitempty"`
	// The new fragments
	//
	// DEPRECATED: use groups instead.
	//
	// These fragments IDs are not yet assigned.
	NewFragments []*DataFragment `protobuf:"bytes,2,rep,name=new_fragments,json=newFragments,proto3" json:"new_fragments,omitempty"`
	// Groups of files that have been rewritten
	Groups []*Transaction_Rewrite_RewriteGroup `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	// Indices that have been rewritten
	RewrittenIndices []*Transaction_Rewrite_RewrittenIndex `protobuf:"bytes,4,rep,name=rewritten_indices,json=rewrittenIndices,proto3" json:"rewritten_indices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transaction_Rewrite) Reset() {
	*x = Transaction_Rewrite{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Rewrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Rewrite) ProtoMessage() {}

func (x *Transaction_Rewrite) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Rewrite.ProtoReflect.Descriptor instead.
func (*Transaction_Rewrite) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Transaction_Rewrite) GetOldFragments() []*DataFragment {
	if x != nil {
		return x.OldFragments
	}
	return nil
}

func (x *Transaction_Rewrite) GetNewFragments() []*DataFragment {
	if x != nil {
		return x.NewFragments
	}
	return nil
}

func (x *Transaction_Rewrite) GetGroups() []*Transaction_Rewrite_RewriteGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Transaction_Rewrite) GetRewrittenIndices() []*Transaction_Rewrite_RewrittenIndex {
	if x != nil {
		return x.RewrittenIndices
	}
	return nil
}

// An operation that merges in a new column, altering the schema.
type Transaction_Merge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated fragments
	//
	// These should all have existing fragment IDs.
	Fragments []*DataFragment `protobuf:"bytes,1,rep,name=fragments,proto3" json:"fragments,omitempty"`
	// The new schema
	Schema []*Field `protobuf:"bytes,2,rep,name=schema,proto3" json:"schema,omitempty"`
	// Schema metadata.
	SchemaMetadata map[string][]byte `protobuf:"bytes,3,rep,name=schema_metadata,json=schemaMetadata,proto3" json:"schema_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction_Merge) Reset() {
	*x = Transaction_Merge{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Merge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Merge) ProtoMessage() {}

func (x *Transaction_Merge) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Merge.ProtoReflect.Descriptor instead.
func (*Transaction_Merge) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Transaction_Merge) GetFragments() []*DataFragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

func (x *Transaction_Merge) GetSchema() []*Field {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Transaction_Merge) GetSchemaMetadata() map[string][]byte {
	if x != nil {
		return x.SchemaMetadata
	}
	return nil
}

// An operation that projects a subset of columns, altering the schema.
type Transaction_Project struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new schema
	Schema        []*Field `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Project) Reset() {
	*x = Transaction_Project{}
	mi := &file_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Project) ProtoMessage() {}

func (x *Transaction_Project) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Project.ProtoReflect.Descriptor instead.
func (*Transaction_Project) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Transaction_Project) GetSchema() []*Field {
	if x != nil {
		return x.Schema
	}
	return nil
}

// An operation that restores a dataset to a previous version.
type Transaction_Restore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version to restore to
	Version       uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Restore) Reset() {
	*x = Transaction_Restore{}
	mi := &file_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Restore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Restore) ProtoMessage() {}

func (x *Transaction_Restore) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Restore.ProtoReflect.Descriptor instead.
func (*Transaction_Restore) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Transaction_Restore) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// An operation that reserves fragment ids for future use in
// a rewrite operation.
type Transaction_ReserveFragments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumFragments  uint32                 `protobuf:"varint,1,opt,name=num_fragments,json=numFragments,proto3" json:"num_fragments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_ReserveFragments) Reset() {
	*x = Transaction_ReserveFragments{}
	mi := &file_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_ReserveFragments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_ReserveFragments) ProtoMessage() {}

func (x *Transaction_ReserveFragments) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_ReserveFragments.ProtoReflect.Descriptor instead.
func (*Transaction_ReserveFragments) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Transaction_ReserveFragments) GetNumFragments() uint32 {
	if x != nil {
		return x.NumFragments
	}
	return 0
}

// An operation that clones a dataset.
type Transaction_Clone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//   - true:  Performs a metadata-only clone (copies manifest without data files).
	//     The cloned dataset references original data through `base_paths`,
	//     suitable for experimental scenarios or rapid metadata migration.
	//   - false: Performs a full deep clone using the underlying object storage's native
	//     copy API (e.g., S3 CopyObject, GCS rewrite). This leverages server-side
	//     bulk copy operations to bypass download/upload bottlenecks, achieving
	//     near-linear speedup for large datasets (typically 3-10x faster than
	//     manual file transfers). The operation maintains atomicity and data
	//     integrity guarantees provided by the storage backend.
	IsShallow bool `protobuf:"varint,1,opt,name=is_shallow,json=isShallow,proto3" json:"is_shallow,omitempty"`
	// the reference name in the source dataset
	// in most cases it should be the branch or tag name in the source dataset
	RefName *string `protobuf:"bytes,2,opt,name=ref_name,json=refName,proto3,oneof" json:"ref_name,omitempty"`
	// the version of the source dataset for cloning
	RefVersion uint64 `protobuf:"varint,3,opt,name=ref_version,json=refVersion,proto3" json:"ref_version,omitempty"`
	// the absolute base path of the source dataset for cloning
	RefPath string `protobuf:"bytes,4,opt,name=ref_path,json=refPath,proto3" json:"ref_path,omitempty"`
	// if the target dataset is a branch, this is the branch name of the target dataset
	BranchName    *string `protobuf:"bytes,5,opt,name=branch_name,json=branchName,proto3,oneof" json:"branch_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Clone) Reset() {
	*x = Transaction_Clone{}
	mi := &file_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Clone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Clone) ProtoMessage() {}

func (x *Transaction_Clone) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Clone.ProtoReflect.Descriptor instead.
func (*Transaction_Clone) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Transaction_Clone) GetIsShallow() bool {
	if x != nil {
		return x.IsShallow
	}
	return false
}

func (x *Transaction_Clone) GetRefName() string {
	if x != nil && x.RefName != nil {
		return *x.RefName
	}
	return ""
}

func (x *Transaction_Clone) GetRefVersion() uint64 {
	if x != nil {
		return x.RefVersion
	}
	return 0
}

func (x *Transaction_Clone) GetRefPath() string {
	if x != nil {
		return x.RefPath
	}
	return ""
}

func (x *Transaction_Clone) GetBranchName() string {
	if x != nil && x.BranchName != nil {
		return *x.BranchName
	}
	return ""
}

// Exact set of key hashes for conflict detection.
// Used when the number of inserted rows is small.
type Transaction_ExactKeySetFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 64-bit hashes of the inserted row keys.
	KeyHashes     []uint64 `protobuf:"varint,1,rep,packed,name=key_hashes,json=keyHashes,proto3" json:"key_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_ExactKeySetFilter) Reset() {
	*x = Transaction_ExactKeySetFilter{}
	mi := &file_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_ExactKeySetFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_ExactKeySetFilter) ProtoMessage() {}

func (x *Transaction_ExactKeySetFilter) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_ExactKeySetFilter.ProtoReflect.Descriptor instead.
func (*Transaction_ExactKeySetFilter) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Transaction_ExactKeySetFilter) GetKeyHashes() []uint64 {
	if x != nil {
		return x.KeyHashes
	}
	return nil
}

// Bloom filter for key existence tests.
// Used when the number of rows is large.
type Transaction_BloomFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bitset backing the bloom filter (SBBF format).
	Bitmap []byte `protobuf:"bytes,1,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	// Number of bits in the bitmap.
	NumBits uint32 `protobuf:"varint,2,opt,name=num_bits,json=numBits,proto3" json:"num_bits,omitempty"`
	// Number of items the filter was sized for.
	// Used for intersection validation (filters with different sizes cannot be compared).
	// Default: 8192
	NumberOfItems uint64 `protobuf:"varint,3,opt,name=number_of_items,json=numberOfItems,proto3" json:"number_of_items,omitempty"`
	// False positive probability the filter was sized for.
	// Used for intersection validation (filters with different parameters cannot be compared).
	// Default: 0.00057
	Probability   float64 `protobuf:"fixed64,4,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_BloomFilter) Reset() {
	*x = Transaction_BloomFilter{}
	mi := &file_transaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_BloomFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_BloomFilter) ProtoMessage() {}

func (x *Transaction_BloomFilter) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_BloomFilter.ProtoReflect.Descriptor instead.
func (*Transaction_BloomFilter) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 12}
}

func (x *Transaction_BloomFilter) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

func (x *Transaction_BloomFilter) GetNumBits() uint32 {
	if x != nil {
		return x.NumBits
	}
	return 0
}

func (x *Transaction_BloomFilter) GetNumberOfItems() uint64 {
	if x != nil {
		return x.NumberOfItems
	}
	return 0
}

func (x *Transaction_BloomFilter) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

// A filter for checking key existence in set of rows inserted by a merge insert operation.
// Only created when the merge insert's ON columns match the schema's unenforced primary key.
// The presence of this filter indicates strict primary key conflict detection should be used.
// Can use either an exact set (for small row counts) or a Bloom filter (for large row counts).
type Transaction_KeyExistenceFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field IDs of columns participating in the key (must match unenforced primary key).
	FieldIds []int32 `protobuf:"varint,1,rep,packed,name=field_ids,json=fieldIds,proto3" json:"field_ids,omitempty"`
	// The underlying data structure storing the key hashes.
	//
	// Types that are valid to be assigned to Data:
	//
	//	*Transaction_KeyExistenceFilter_Exact
	//	*Transaction_KeyExistenceFilter_Bloom
	Data          isTransaction_KeyExistenceFilter_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_KeyExistenceFilter) Reset() {
	*x = Transaction_KeyExistenceFilter{}
	mi := &file_transaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_KeyExistenceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_KeyExistenceFilter) ProtoMessage() {}

func (x *Transaction_KeyExistenceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_KeyExistenceFilter.ProtoReflect.Descriptor instead.
func (*Transaction_KeyExistenceFilter) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 13}
}

func (x *Transaction_KeyExistenceFilter) GetFieldIds() []int32 {
	if x != nil {
		return x.FieldIds
	}
	return nil
}

func (x *Transaction_KeyExistenceFilter) GetData() isTransaction_KeyExistenceFilter_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction_KeyExistenceFilter) GetExact() *Transaction_ExactKeySetFilter {
	if x != nil {
		if x, ok := x.Data.(*Transaction_KeyExistenceFilter_Exact); ok {
			return x.Exact
		}
	}
	return nil
}

func (x *Transaction_KeyExistenceFilter) GetBloom() *Transaction_BloomFilter {
	if x != nil {
		if x, ok := x.Data.(*Transaction_KeyExistenceFilter_Bloom); ok {
			return x.Bloom
		}
	}
	return nil
}

type isTransaction_KeyExistenceFilter_Data interface {
	isTransaction_KeyExistenceFilter_Data()
}

type Transaction_KeyExistenceFilter_Exact struct {
	// Exact set of key hashes (used for small number of rows).
	Exact *Transaction_ExactKeySetFilter `protobuf:"bytes,2,opt,name=exact,proto3,oneof"`
}

type Transaction_KeyExistenceFilter_Bloom struct {
	// Bloom filter (used for large number of rows).
	Bloom *Transaction_BloomFilter `protobuf:"bytes,3,opt,name=bloom,proto3,oneof"`
}

func (*Transaction_KeyExistenceFilter_Exact) isTransaction_KeyExistenceFilter_Data() {}

func (*Transaction_KeyExistenceFilter_Bloom) isTransaction_KeyExistenceFilter_Data() {}

// An operation that updates rows but does not add or remove rows.
type Transaction_Update struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fragments that have been removed. These are fragments where all rows
	// have been updated and moved to a new fragment.
	RemovedFragmentIds []uint64 `protobuf:"varint,1,rep,packed,name=removed_fragment_ids,json=removedFragmentIds,proto3" json:"removed_fragment_ids,omitempty"`
	// The fragments that have been updated.
	UpdatedFragments []*DataFragment `protobuf:"bytes,2,rep,name=updated_fragments,json=updatedFragments,proto3" json:"updated_fragments,omitempty"`
	// The new fragments where updated rows have been moved to.
	NewFragments []*DataFragment `protobuf:"bytes,3,rep,name=new_fragments,json=newFragments,proto3" json:"new_fragments,omitempty"`
	// The ids of the fields that have been modified.
	FieldsModified []uint32 `protobuf:"varint,4,rep,packed,name=fields_modified,json=fieldsModified,proto3" json:"fields_modified,omitempty"`
	// / List of MemWAL region generations to mark as merged after this transaction
	MergedGenerations []*MergedGeneration `protobuf:"bytes,5,rep,name=merged_generations,json=mergedGenerations,proto3" json:"merged_generations,omitempty"`
	// / The fields that used to judge whether to preserve the new frag's id into
	// / the frag bitmap of the specified indices.
	FieldsForPreservingFragBitmap []uint32 `protobuf:"varint,6,rep,packed,name=fields_for_preserving_frag_bitmap,json=fieldsForPreservingFragBitmap,proto3" json:"fields_for_preserving_frag_bitmap,omitempty"`
	// The mode of update
	UpdateMode Transaction_UpdateMode `protobuf:"varint,7,opt,name=update_mode,json=updateMode,proto3,enum=lance.table.Transaction_UpdateMode" json:"update_mode,omitempty"`
	// Filter for checking existence of keys in newly inserted rows, used for conflict detection.
	// Only tracks keys from INSERT operations during merge insert, not updates.
	InsertedRows  *Transaction_KeyExistenceFilter `protobuf:"bytes,8,opt,name=inserted_rows,json=insertedRows,proto3,oneof" json:"inserted_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Update) Reset() {
	*x = Transaction_Update{}
	mi := &file_transaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Update) ProtoMessage() {}

func (x *Transaction_Update) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Update.ProtoReflect.Descriptor instead.
func (*Transaction_Update) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 14}
}

func (x *Transaction_Update) GetRemovedFragmentIds() []uint64 {
	if x != nil {
		return x.RemovedFragmentIds
	}
	return nil
}

func (x *Transaction_Update) GetUpdatedFragments() []*DataFragment {
	if x != nil {
		return x.UpdatedFragments
	}
	return nil
}

func (x *Transaction_Update) GetNewFragments() []*DataFragment {
	if x != nil {
		return x.NewFragments
	}
	return nil
}

func (x *Transaction_Update) GetFieldsModified() []uint32 {
	if x != nil {
		return x.FieldsModified
	}
	return nil
}

func (x *Transaction_Update) GetMergedGenerations() []*MergedGeneration {
	if x != nil {
		return x.MergedGenerations
	}
	return nil
}

func (x *Transaction_Update) GetFieldsForPreservingFragBitmap() []uint32 {
	if x != nil {
		return x.FieldsForPreservingFragBitmap
	}
	return nil
}

func (x *Transaction_Update) GetUpdateMode() Transaction_UpdateMode {
	if x != nil {
		return x.UpdateMode
	}
	return Transaction_REWRITE_ROWS
}

func (x *Transaction_Update) GetInsertedRows() *Transaction_KeyExistenceFilter {
	if x != nil {
		return x.InsertedRows
	}
	return nil
}

// An entry for a map update. If value is not set, the key will be removed from the map.
type Transaction_UpdateMapEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the map entry to update.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value to set for the key.
	Value         *string `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_UpdateMapEntry) Reset() {
	*x = Transaction_UpdateMapEntry{}
	mi := &file_transaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_UpdateMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_UpdateMapEntry) ProtoMessage() {}

func (x *Transaction_UpdateMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_UpdateMapEntry.ProtoReflect.Descriptor instead.
func (*Transaction_UpdateMapEntry) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 15}
}

func (x *Transaction_UpdateMapEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Transaction_UpdateMapEntry) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type Transaction_UpdateMap struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	UpdateEntries []*Transaction_UpdateMapEntry `protobuf:"bytes,1,rep,name=update_entries,json=updateEntries,proto3" json:"update_entries,omitempty"`
	// If true, the map will be replaced entirely with the new entries.
	// If false, the new entries will be merged with the existing map.
	Replace       bool `protobuf:"varint,2,opt,name=replace,proto3" json:"replace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_UpdateMap) Reset() {
	*x = Transaction_UpdateMap{}
	mi := &file_transaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_UpdateMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_UpdateMap) ProtoMessage() {}

func (x *Transaction_UpdateMap) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_UpdateMap.ProtoReflect.Descriptor instead.
func (*Transaction_UpdateMap) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 16}
}

func (x *Transaction_UpdateMap) GetUpdateEntries() []*Transaction_UpdateMapEntry {
	if x != nil {
		return x.UpdateEntries
	}
	return nil
}

func (x *Transaction_UpdateMap) GetReplace() bool {
	if x != nil {
		return x.Replace
	}
	return false
}

// An operation that updates the table config, table metadata, schema metadata,
// or field metadata.
type Transaction_UpdateConfig struct {
	state                 protoimpl.MessageState           `protogen:"open.v1"`
	ConfigUpdates         *Transaction_UpdateMap           `protobuf:"bytes,6,opt,name=config_updates,json=configUpdates,proto3" json:"config_updates,omitempty"`
	TableMetadataUpdates  *Transaction_UpdateMap           `protobuf:"bytes,7,opt,name=table_metadata_updates,json=tableMetadataUpdates,proto3" json:"table_metadata_updates,omitempty"`
	SchemaMetadataUpdates *Transaction_UpdateMap           `protobuf:"bytes,8,opt,name=schema_metadata_updates,json=schemaMetadataUpdates,proto3" json:"schema_metadata_updates,omitempty"`
	FieldMetadataUpdates  map[int32]*Transaction_UpdateMap `protobuf:"bytes,9,rep,name=field_metadata_updates,json=fieldMetadataUpdates,proto3" json:"field_metadata_updates,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated -------------------------------
	UpsertValues   map[string]string                                        `protobuf:"bytes,1,rep,name=upsert_values,json=upsertValues,proto3" json:"upsert_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeleteKeys     []string                                                 `protobuf:"bytes,2,rep,name=delete_keys,json=deleteKeys,proto3" json:"delete_keys,omitempty"`
	SchemaMetadata map[string]string                                        `protobuf:"bytes,3,rep,name=schema_metadata,json=schemaMetadata,proto3" json:"schema_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FieldMetadata  map[uint32]*Transaction_UpdateConfig_FieldMetadataUpdate `protobuf:"bytes,4,rep,name=field_metadata,json=fieldMetadata,proto3" json:"field_metadata,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction_UpdateConfig) Reset() {
	*x = Transaction_UpdateConfig{}
	mi := &file_transaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_UpdateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_UpdateConfig) ProtoMessage() {}

func (x *Transaction_UpdateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_UpdateConfig.ProtoReflect.Descriptor instead.
func (*Transaction_UpdateConfig) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 17}
}

func (x *Transaction_UpdateConfig) GetConfigUpdates() *Transaction_UpdateMap {
	if x != nil {
		return x.ConfigUpdates
	}
	return nil
}

func (x *Transaction_UpdateConfig) GetTableMetadataUpdates() *Transaction_UpdateMap {
	if x != nil {
		return x.TableMetadataUpdates
	}
	return nil
}

func (x *Transaction_UpdateConfig) GetSchemaMetadataUpdates() *Transaction_UpdateMap {
	if x != nil {
		return x.SchemaMetadataUpdates
	}
	return nil
}

func (x *Transaction_UpdateConfig) GetFieldMetadataUpdates() map[int32]*Transaction_UpdateMap {
	if x != nil {
		return x.FieldMetadataUpdates
	}
	return nil
}

func (x *Transaction_UpdateConfig) GetUpsertValues() map[string]string {
	if x != nil {
		return x.UpsertValues
	}
	return nil
}

func (x *Transaction_UpdateConfig) GetDeleteKeys() []string {
	if x != nil {
		return x.DeleteKeys
	}
	return nil
}

func (x *Transaction_UpdateConfig) GetSchemaMetadata() map[string]string {
	if x != nil {
		return x.SchemaMetadata
	}
	return nil
}

func (x *Transaction_UpdateConfig) GetFieldMetadata() map[uint32]*Transaction_UpdateConfig_FieldMetadataUpdate {
	if x != nil {
		return x.FieldMetadata
	}
	return nil
}

type Transaction_DataReplacementGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FragmentId    uint64                 `protobuf:"varint,1,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	NewFile       *DataFile              `protobuf:"bytes,2,opt,name=new_file,json=newFile,proto3" json:"new_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_DataReplacementGroup) Reset() {
	*x = Transaction_DataReplacementGroup{}
	mi := &file_transaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_DataReplacementGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_DataReplacementGroup) ProtoMessage() {}

func (x *Transaction_DataReplacementGroup) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_DataReplacementGroup.ProtoReflect.Descriptor instead.
func (*Transaction_DataReplacementGroup) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 18}
}

func (x *Transaction_DataReplacementGroup) GetFragmentId() uint64 {
	if x != nil {
		return x.FragmentId
	}
	return 0
}

func (x *Transaction_DataReplacementGroup) GetNewFile() *DataFile {
	if x != nil {
		return x.NewFile
	}
	return nil
}

// An operation that replaces the data in a region of the table with new data.
type Transaction_DataReplacement struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Replacements  []*Transaction_DataReplacementGroup `protobuf:"bytes,1,rep,name=replacements,proto3" json:"replacements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_DataReplacement) Reset() {
	*x = Transaction_DataReplacement{}
	mi := &file_transaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_DataReplacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_DataReplacement) ProtoMessage() {}

func (x *Transaction_DataReplacement) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_DataReplacement.ProtoReflect.Descriptor instead.
func (*Transaction_DataReplacement) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 19}
}

func (x *Transaction_DataReplacement) GetReplacements() []*Transaction_DataReplacementGroup {
	if x != nil {
		return x.Replacements
	}
	return nil
}

// Update the merged generations in MemWAL index.
// This operation is used during merge-insert to atomically record which
// generations have been merged to the base table.
type Transaction_UpdateMemWalState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Regions and generations being marked as merged.
	MergedGenerations []*MergedGeneration `protobuf:"bytes,1,rep,name=merged_generations,json=mergedGenerations,proto3" json:"merged_generations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Transaction_UpdateMemWalState) Reset() {
	*x = Transaction_UpdateMemWalState{}
	mi := &file_transaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_UpdateMemWalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_UpdateMemWalState) ProtoMessage() {}

func (x *Transaction_UpdateMemWalState) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_UpdateMemWalState.ProtoReflect.Descriptor instead.
func (*Transaction_UpdateMemWalState) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 20}
}

func (x *Transaction_UpdateMemWalState) GetMergedGenerations() []*MergedGeneration {
	if x != nil {
		return x.MergedGenerations
	}
	return nil
}

// An operation that updates base paths in the dataset.
type Transaction_UpdateBases struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new base paths to add to the manifest.
	NewBases      []*BasePath `protobuf:"bytes,1,rep,name=new_bases,json=newBases,proto3" json:"new_bases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_UpdateBases) Reset() {
	*x = Transaction_UpdateBases{}
	mi := &file_transaction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_UpdateBases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_UpdateBases) ProtoMessage() {}

func (x *Transaction_UpdateBases) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_UpdateBases.ProtoReflect.Descriptor instead.
func (*Transaction_UpdateBases) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 21}
}

func (x *Transaction_UpdateBases) GetNewBases() []*BasePath {
	if x != nil {
		return x.NewBases
	}
	return nil
}

// During a rewrite an index may be rewritten.  We only serialize the UUID
// since a rewrite should not change the other index parameters.
type Transaction_Rewrite_RewrittenIndex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the index that will be replaced
	OldId *UUID `protobuf:"bytes,1,opt,name=old_id,json=oldId,proto3" json:"old_id,omitempty"`
	// the id of the new index
	NewId *UUID `protobuf:"bytes,2,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
	// the new index details
	NewIndexDetails *anypb.Any `protobuf:"bytes,3,opt,name=new_index_details,json=newIndexDetails,proto3" json:"new_index_details,omitempty"`
	// the version of the new index
	NewIndexVersion uint32 `protobuf:"varint,4,opt,name=new_index_version,json=newIndexVersion,proto3" json:"new_index_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction_Rewrite_RewrittenIndex) Reset() {
	*x = Transaction_Rewrite_RewrittenIndex{}
	mi := &file_transaction_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Rewrite_RewrittenIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Rewrite_RewrittenIndex) ProtoMessage() {}

func (x *Transaction_Rewrite_RewrittenIndex) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Rewrite_RewrittenIndex.ProtoReflect.Descriptor instead.
func (*Transaction_Rewrite_RewrittenIndex) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 5, 0}
}

func (x *Transaction_Rewrite_RewrittenIndex) GetOldId() *UUID {
	if x != nil {
		return x.OldId
	}
	return nil
}

func (x *Transaction_Rewrite_RewrittenIndex) GetNewId() *UUID {
	if x != nil {
		return x.NewId
	}
	return nil
}

func (x *Transaction_Rewrite_RewrittenIndex) GetNewIndexDetails() *anypb.Any {
	if x != nil {
		return x.NewIndexDetails
	}
	return nil
}

func (x *Transaction_Rewrite_RewrittenIndex) GetNewIndexVersion() uint32 {
	if x != nil {
		return x.NewIndexVersion
	}
	return 0
}

// A group of rewrite files that are all part of the same rewrite.
type Transaction_Rewrite_RewriteGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The old fragment that is being replaced
	//
	// This should have an existing fragment ID.
	OldFragments []*DataFragment `protobuf:"bytes,1,rep,name=old_fragments,json=oldFragments,proto3" json:"old_fragments,omitempty"`
	// The new fragment
	//
	// The ID should have been reserved by an earlier
	// reserve operation
	NewFragments  []*DataFragment `protobuf:"bytes,2,rep,name=new_fragments,json=newFragments,proto3" json:"new_fragments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Rewrite_RewriteGroup) Reset() {
	*x = Transaction_Rewrite_RewriteGroup{}
	mi := &file_transaction_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Rewrite_RewriteGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Rewrite_RewriteGroup) ProtoMessage() {}

func (x *Transaction_Rewrite_RewriteGroup) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Rewrite_RewriteGroup.ProtoReflect.Descriptor instead.
func (*Transaction_Rewrite_RewriteGroup) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 5, 1}
}

func (x *Transaction_Rewrite_RewriteGroup) GetOldFragments() []*DataFragment {
	if x != nil {
		return x.OldFragments
	}
	return nil
}

func (x *Transaction_Rewrite_RewriteGroup) GetNewFragments() []*DataFragment {
	if x != nil {
		return x.NewFragments
	}
	return nil
}

type Transaction_UpdateConfig_FieldMetadataUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_UpdateConfig_FieldMetadataUpdate) Reset() {
	*x = Transaction_UpdateConfig_FieldMetadataUpdate{}
	mi := &file_transaction_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_UpdateConfig_FieldMetadataUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_UpdateConfig_FieldMetadataUpdate) ProtoMessage() {}

func (x *Transaction_UpdateConfig_FieldMetadataUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_UpdateConfig_FieldMetadataUpdate.ProtoReflect.Descriptor instead.
func (*Transaction_UpdateConfig_FieldMetadataUpdate) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 17, 4}
}

func (x *Transaction_UpdateConfig_FieldMetadataUpdate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\vlance.table\x1a\n" +
	"file.proto\x1a\vtable.proto\x1a\x19google/protobuf/any.proto\"\xee1\n" +
	"\vTransaction\x12!\n" +
	"\fread_version\x18\x01 \x01(\x04R\vreadVersion\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12j\n" +
	"\x16transaction_properties\x18\x04 \x03(\v23.lance.table.Transaction.TransactionPropertiesEntryR\x15transactionProperties\x129\n" +
	"\x06append\x18d \x01(\v2\x1f.lance.table.Transaction.AppendH\x00R\x06append\x129\n" +
	"\x06delete\x18e \x01(\v2\x1f.lance.table.Transaction.DeleteH\x00R\x06delete\x12B\n" +
	"\toverwrite\x18f \x01(\v2\".lance.table.Transaction.OverwriteH\x00R\toverwrite\x12I\n" +
	"\fcreate_index\x18g \x01(\v2$.lance.table.Transaction.CreateIndexH\x00R\vcreateIndex\x12<\n" +
	"\arewrite\x18h \x01(\v2 .lance.table.Transaction.RewriteH\x00R\arewrite\x126\n" +
	"\x05merge\x18i \x01(\v2\x1e.lance.table.Transaction.MergeH\x00R\x05merge\x12<\n" +
	"\arestore\x18j \x01(\v2 .lance.table.Transaction.RestoreH\x00R\arestore\x12X\n" +
	"\x11reserve_fragments\x18k \x01(\v2).lance.table.Transaction.ReserveFragmentsH\x00R\x10reserveFragments\x129\n" +
	"\x06update\x18l \x01(\v2\x1f.lance.table.Transaction.UpdateH\x00R\x06update\x12<\n" +
	"\aproject\x18m \x01(\v2 .lance.table.Transaction.ProjectH\x00R\aproject\x12L\n" +
	"\rupdate_config\x18n \x01(\v2%.lance.table.Transaction.UpdateConfigH\x00R\fupdateConfig\x12U\n" +
	"\x10data_replacement\x18o \x01(\v2(.lance.table.Transaction.DataReplacementH\x00R\x0fdataReplacement\x12]\n" +
	"\x14update_mem_wal_state\x18p \x01(\v2*.lance.table.Transaction.UpdateMemWalStateH\x00R\x11updateMemWalState\x126\n" +
	"\x05clone\x18q \x01(\v2\x1e.lance.table.Transaction.CloneH\x00R\x05clone\x12I\n" +
	"\fupdate_bases\x18r \x01(\v2$.lance.table.Transaction.UpdateBasesH\x00R\vupdateBases\x1aH\n" +
	"\x1aTransactionPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x06Append\x127\n" +
	"\tfragments\x18\x01 \x03(\v2\x19.lance.table.DataFragmentR\tfragments\x1a\xa0\x01\n" +
	"\x06Delete\x12F\n" +
	"\x11updated_fragments\x18\x01 \x03(\v2\x19.lance.table.DataFragmentR\x10updatedFragments\x120\n" +
	"\x14deleted_fragment_ids\x18\x02 \x03(\x04R\x12deletedFragmentIds\x12\x1c\n" +
	"\tpredicate\x18\x03 \x01(\tR\tpredicate\x1a\x84\x04\n" +
	"\tOverwrite\x127\n" +
	"\tfragments\x18\x01 \x03(\v2\x19.lance.table.DataFragmentR\tfragments\x12)\n" +
	"\x06schema\x18\x02 \x03(\v2\x11.lance.file.FieldR\x06schema\x12_\n" +
	"\x0fschema_metadata\x18\x03 \x03(\v26.lance.table.Transaction.Overwrite.SchemaMetadataEntryR\x0eschemaMetadata\x12l\n" +
	"\x14config_upsert_values\x18\x04 \x03(\v2:.lance.table.Transaction.Overwrite.ConfigUpsertValuesEntryR\x12configUpsertValues\x12:\n" +
	"\rinitial_bases\x18\x05 \x03(\v2\x15.lance.table.BasePathR\finitialBases\x1aA\n" +
	"\x13SchemaMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aE\n" +
	"\x17ConfigUpsertValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\x8f\x01\n" +
	"\vCreateIndex\x12;\n" +
	"\vnew_indices\x18\x01 \x03(\v2\x1a.lance.table.IndexMetadataR\n" +
	"newIndices\x12C\n" +
	"\x0fremoved_indices\x18\x02 \x03(\v2\x1a.lance.table.IndexMetadataR\x0eremovedIndices\x1a\x94\x05\n" +
	"\aRewrite\x12>\n" +
	"\rold_fragments\x18\x01 \x03(\v2\x19.lance.table.DataFragmentR\foldFragments\x12>\n" +
	"\rnew_fragments\x18\x02 \x03(\v2\x19.lance.table.DataFragmentR\fnewFragments\x12E\n" +
	"\x06groups\x18\x03 \x03(\v2-.lance.table.Transaction.Rewrite.RewriteGroupR\x06groups\x12\\\n" +
	"\x11rewritten_indices\x18\x04 \x03(\v2/.lance.table.Transaction.Rewrite.RewrittenIndexR\x10rewrittenIndices\x1a\xd2\x01\n" +
	"\x0eRewrittenIndex\x12(\n" +
	"\x06old_id\x18\x01 \x01(\v2\x11.lance.table.UUIDR\x05oldId\x12(\n" +
	"\x06new_id\x18\x02 \x01(\v2\x11.lance.table.UUIDR\x05newId\x12@\n" +
	"\x11new_index_details\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x0fnewIndexDetails\x12*\n" +
	"\x11new_index_version\x18\x04 \x01(\rR\x0fnewIndexVersion\x1a\x8e\x01\n" +
	"\fRewriteGroup\x12>\n" +
	"\rold_fragments\x18\x01 \x03(\v2\x19.lance.table.DataFragmentR\foldFragments\x12>\n" +
	"\rnew_fragments\x18\x02 \x03(\v2\x19.lance.table.DataFragmentR\fnewFragments\x1a\x8b\x02\n" +
	"\x05Merge\x127\n" +
	"\tfragments\x18\x01 \x03(\v2\x19.lance.table.DataFragmentR\tfragments\x12)\n" +
	"\x06schema\x18\x02 \x03(\v2\x11.lance.file.FieldR\x06schema\x12[\n" +
	"\x0fschema_metadata\x18\x03 \x03(\v22.lance.table.Transaction.Merge.SchemaMetadataEntryR\x0eschemaMetadata\x1aA\n" +
	"\x13SchemaMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a4\n" +
	"\aProject\x12)\n" +
	"\x06schema\x18\x01 \x03(\v2\x11.lance.file.FieldR\x06schema\x1a#\n" +
	"\aRestore\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x1a7\n" +
	"\x10ReserveFragments\x12#\n" +
	"\rnum_fragments\x18\x01 \x01(\rR\fnumFragments\x1a\xc5\x01\n" +
	"\x05Clone\x12\x1d\n" +
	"\n" +
	"is_shallow\x18\x01 \x01(\bR\tisShallow\x12\x1e\n" +
	"\bref_name\x18\x02 \x01(\tH\x00R\arefName\x88\x01\x01\x12\x1f\n" +
	"\vref_version\x18\x03 \x01(\x04R\n" +
	"refVersion\x12\x19\n" +
	"\bref_path\x18\x04 \x01(\tR\arefPath\x12$\n" +
	"\vbranch_name\x18\x05 \x01(\tH\x01R\n" +
	"branchName\x88\x01\x01B\v\n" +
	"\t_ref_nameB\x0e\n" +
	"\f_branch_name\x1a2\n" +
	"\x11ExactKeySetFilter\x12\x1d\n" +
	"\n" +
	"key_hashes\x18\x01 \x03(\x04R\tkeyHashes\x1a\x8a\x01\n" +
	"\vBloomFilter\x12\x16\n" +
	"\x06bitmap\x18\x01 \x01(\fR\x06bitmap\x12\x19\n" +
	"\bnum_bits\x18\x02 \x01(\rR\anumBits\x12&\n" +
	"\x0fnumber_of_items\x18\x03 \x01(\x04R\rnumberOfItems\x12 \n" +
	"\vprobability\x18\x04 \x01(\x01R\vprobability\x1a\xbb\x01\n" +
	"\x12KeyExistenceFilter\x12\x1b\n" +
	"\tfield_ids\x18\x01 \x03(\x05R\bfieldIds\x12B\n" +
	"\x05exact\x18\x02 \x01(\v2*.lance.table.Transaction.ExactKeySetFilterH\x00R\x05exact\x12<\n" +
	"\x05bloom\x18\x03 \x01(\v2$.lance.table.Transaction.BloomFilterH\x00R\x05bloomB\x06\n" +
	"\x04data\x1a\xb2\x04\n" +
	"\x06Update\x120\n" +
	"\x14removed_fragment_ids\x18\x01 \x03(\x04R\x12removedFragmentIds\x12F\n" +
	"\x11updated_fragments\x18\x02 \x03(\v2\x19.lance.table.DataFragmentR\x10updatedFragments\x12>\n" +
	"\rnew_fragments\x18\x03 \x03(\v2\x19.lance.table.DataFragmentR\fnewFragments\x12'\n" +
	"\x0ffields_modified\x18\x04 \x03(\rR\x0efieldsModified\x12L\n" +
	"\x12merged_generations\x18\x05 \x03(\v2\x1d.lance.table.MergedGenerationR\x11mergedGenerations\x12H\n" +
	"!fields_for_preserving_frag_bitmap\x18\x06 \x03(\rR\x1dfieldsForPreservingFragBitmap\x12D\n" +
	"\vupdate_mode\x18\a \x01(\x0e2#.lance.table.Transaction.UpdateModeR\n" +
	"updateMode\x12U\n" +
	"\rinserted_rows\x18\b \x01(\v2+.lance.table.Transaction.KeyExistenceFilterH\x00R\finsertedRows\x88\x01\x01B\x10\n" +
	"\x0e_inserted_rows\x1aG\n" +
	"\x0eUpdateMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\x1au\n" +
	"\tUpdateMap\x12N\n" +
	"\x0eupdate_entries\x18\x01 \x03(\v2'.lance.table.Transaction.UpdateMapEntryR\rupdateEntries\x12\x18\n" +
	"\areplace\x18\x02 \x01(\bR\areplace\x1a\xf2\t\n" +
	"\fUpdateConfig\x12I\n" +
	"\x0econfig_updates\x18\x06 \x01(\v2\".lance.table.Transaction.UpdateMapR\rconfigUpdates\x12X\n" +
	"\x16table_metadata_updates\x18\a \x01(\v2\".lance.table.Transaction.UpdateMapR\x14tableMetadataUpdates\x12Z\n" +
	"\x17schema_metadata_updates\x18\b \x01(\v2\".lance.table.Transaction.UpdateMapR\x15schemaMetadataUpdates\x12u\n" +
	"\x16field_metadata_updates\x18\t \x03(\v2?.lance.table.Transaction.UpdateConfig.FieldMetadataUpdatesEntryR\x14fieldMetadataUpdates\x12\\\n" +
	"\rupsert_values\x18\x01 \x03(\v27.lance.table.Transaction.UpdateConfig.UpsertValuesEntryR\fupsertValues\x12\x1f\n" +
	"\vdelete_keys\x18\x02 \x03(\tR\n" +
	"deleteKeys\x12b\n" +
	"\x0fschema_metadata\x18\x03 \x03(\v29.lance.table.Transaction.UpdateConfig.SchemaMetadataEntryR\x0eschemaMetadata\x12_\n" +
	"\x0efield_metadata\x18\x04 \x03(\v28.lance.table.Transaction.UpdateConfig.FieldMetadataEntryR\rfieldMetadata\x1ak\n" +
	"\x19FieldMetadataUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".lance.table.Transaction.UpdateMapR\x05value:\x028\x01\x1a?\n" +
	"\x11UpsertValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13SchemaMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a{\n" +
	"\x12FieldMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12O\n" +
	"\x05value\x18\x02 \x01(\v29.lance.table.Transaction.UpdateConfig.FieldMetadataUpdateR\x05value:\x028\x01\x1a\xb7\x01\n" +
	"\x13FieldMetadataUpdate\x12c\n" +
	"\bmetadata\x18\x05 \x03(\v2G.lance.table.Transaction.UpdateConfig.FieldMetadataUpdate.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ai\n" +
	"\x14DataReplacementGroup\x12\x1f\n" +
	"\vfragment_id\x18\x01 \x01(\x04R\n" +
	"fragmentId\x120\n" +
	"\bnew_file\x18\x02 \x01(\v2\x15.lance.table.DataFileR\anewFile\x1ad\n" +
	"\x0fDataReplacement\x12Q\n" +
	"\freplacements\x18\x01 \x03(\v2-.lance.table.Transaction.DataReplacementGroupR\freplacements\x1aa\n" +
	"\x11UpdateMemWalState\x12L\n" +
	"\x12merged_generations\x18\x01 \x03(\v2\x1d.lance.table.MergedGenerationR\x11mergedGenerations\x1aA\n" +
	"\vUpdateBases\x122\n" +
	"\tnew_bases\x18\x01 \x03(\v2\x15.lance.table.BasePathR\bnewBases\"3\n" +
	"\n" +
	"UpdateMode\x12\x10\n" +
	"\fREWRITE_ROWS\x10\x00\x12\x13\n" +
	"\x0fREWRITE_COLUMNS\x10\x01B\v\n" +
	"\toperationJ\x06\b\xc8\x01\x10\xc9\x01J\x06\b\xca\x01\x10\xcb\x01R\vblob_appendR\x0eblob_overwriteB9Z7github.com/daviszhen/plan/pkg/storage2/proto;storage2pbb\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_transaction_proto_goTypes = []any{
	(Transaction_UpdateMode)(0),                // 0: lance.table.Transaction.UpdateMode
	(*Transaction)(nil),                        // 1: lance.table.Transaction
	nil,                                        // 2: lance.table.Transaction.TransactionPropertiesEntry
	(*Transaction_Append)(nil),                 // 3: lance.table.Transaction.Append
	(*Transaction_Delete)(nil),                 // 4: lance.table.Transaction.Delete
	(*Transaction_Overwrite)(nil),              // 5: lance.table.Transaction.Overwrite
	(*Transaction_CreateIndex)(nil),            // 6: lance.table.Transaction.CreateIndex
	(*Transaction_Rewrite)(nil),                // 7: lance.table.Transaction.Rewrite
	(*Transaction_Merge)(nil),                  // 8: lance.table.Transaction.Merge
	(*Transaction_Project)(nil),                // 9: lance.table.Transaction.Project
	(*Transaction_Restore)(nil),                // 10: lance.table.Transaction.Restore
	(*Transaction_ReserveFragments)(nil),       // 11: lance.table.Transaction.ReserveFragments
	(*Transaction_Clone)(nil),                  // 12: lance.table.Transaction.Clone
	(*Transaction_ExactKeySetFilter)(nil),      // 13: lance.table.Transaction.ExactKeySetFilter
	(*Transaction_BloomFilter)(nil),            // 14: lance.table.Transaction.BloomFilter
	(*Transaction_KeyExistenceFilter)(nil),     // 15: lance.table.Transaction.KeyExistenceFilter
	(*Transaction_Update)(nil),                 // 16: lance.table.Transaction.Update
	(*Transaction_UpdateMapEntry)(nil),         // 17: lance.table.Transaction.UpdateMapEntry
	(*Transaction_UpdateMap)(nil),              // 18: lance.table.Transaction.UpdateMap
	(*Transaction_UpdateConfig)(nil),           // 19: lance.table.Transaction.UpdateConfig
	(*Transaction_DataReplacementGroup)(nil),   // 20: lance.table.Transaction.DataReplacementGroup
	(*Transaction_DataReplacement)(nil),        // 21: lance.table.Transaction.DataReplacement
	(*Transaction_UpdateMemWalState)(nil),      // 22: lance.table.Transaction.UpdateMemWalState
	(*Transaction_UpdateBases)(nil),            // 23: lance.table.Transaction.UpdateBases
	nil,                                        // 24: lance.table.Transaction.Overwrite.SchemaMetadataEntry
	nil,                                        // 25: lance.table.Transaction.Overwrite.ConfigUpsertValuesEntry
	(*Transaction_Rewrite_RewrittenIndex)(nil), // 26: lance.table.Transaction.Rewrite.RewrittenIndex
	(*Transaction_Rewrite_RewriteGroup)(nil),   // 27: lance.table.Transaction.Rewrite.RewriteGroup
	nil,                                        // 28: lance.table.Transaction.Merge.SchemaMetadataEntry
	nil,                                        // 29: lance.table.Transaction.UpdateConfig.FieldMetadataUpdatesEntry
	nil,                                        // 30: lance.table.Transaction.UpdateConfig.UpsertValuesEntry
	nil,                                        // 31: lance.table.Transaction.UpdateConfig.SchemaMetadataEntry
	nil,                                        // 32: lance.table.Transaction.UpdateConfig.FieldMetadataEntry
	(*Transaction_UpdateConfig_FieldMetadataUpdate)(nil), // 33: lance.table.Transaction.UpdateConfig.FieldMetadataUpdate
	nil,                      // 34: lance.table.Transaction.UpdateConfig.FieldMetadataUpdate.MetadataEntry
	(*DataFragment)(nil),     // 35: lance.table.DataFragment
	(*Field)(nil),            // 36: lance.file.Field
	(*BasePath)(nil),         // 37: lance.table.BasePath
	(*IndexMetadata)(nil),    // 38: lance.table.IndexMetadata
	(*MergedGeneration)(nil), // 39: lance.table.MergedGeneration
	(*DataFile)(nil),         // 40: lance.table.DataFile
	(*UUID)(nil),             // 41: lance.table.UUID
	(*anypb.Any)(nil),        // 42: google.protobuf.Any
}
var file_transaction_proto_depIdxs = []int32{
	2,  // 0: lance.table.Transaction.transaction_properties:type_name -> lance.table.Transaction.TransactionPropertiesEntry
	3,  // 1: lance.table.Transaction.append:type_name -> lance.table.Transaction.Append
	4,  // 2: lance.table.Transaction.delete:type_name -> lance.table.Transaction.Delete
	5,  // 3: lance.table.Transaction.overwrite:type_name -> lance.table.Transaction.Overwrite
	6,  // 4: lance.table.Transaction.create_index:type_name -> lance.table.Transaction.CreateIndex
	7,  // 5: lance.table.Transaction.rewrite:type_name -> lance.table.Transaction.Rewrite
	8,  // 6: lance.table.Transaction.merge:type_name -> lance.table.Transaction.Merge
	10, // 7: lance.table.Transaction.restore:type_name -> lance.table.Transaction.Restore
	11, // 8: lance.table.Transaction.reserve_fragments:type_name -> lance.table.Transaction.ReserveFragments
	16, // 9: lance.table.Transaction.update:type_name -> lance.table.Transaction.Update
	9,  // 10: lance.table.Transaction.project:type_name -> lance.table.Transaction.Project
	19, // 11: lance.table.Transaction.update_config:type_name -> lance.table.Transaction.UpdateConfig
	21, // 12: lance.table.Transaction.data_replacement:type_name -> lance.table.Transaction.DataReplacement
	22, // 13: lance.table.Transaction.update_mem_wal_state:type_name -> lance.table.Transaction.UpdateMemWalState
	12, // 14: lance.table.Transaction.clone:type_name -> lance.table.Transaction.Clone
	23, // 15: lance.table.Transaction.update_bases:type_name -> lance.table.Transaction.UpdateBases
	35, // 16: lance.table.Transaction.Append.fragments:type_name -> lance.table.DataFragment
	35, // 17: lance.table.Transaction.Delete.updated_fragments:type_name -> lance.table.DataFragment
	35, // 18: lance.table.Transaction.Overwrite.fragments:type_name -> lance.table.DataFragment
	36, // 19: lance.table.Transaction.Overwrite.schema:type_name -> lance.file.Field
	24, // 20: lance.table.Transaction.Overwrite.schema_metadata:type_name -> lance.table.Transaction.Overwrite.SchemaMetadataEntry
	25, // 21: lance.table.Transaction.Overwrite.config_upsert_values:type_name -> lance.table.Transaction.Overwrite.ConfigUpsertValuesEntry
	37, // 22: lance.table.Transaction.Overwrite.initial_bases:type_name -> lance.table.BasePath
	38, // 23: lance.table.Transaction.CreateIndex.new_indices:type_name -> lance.table.IndexMetadata
	38, // 24: lance.table.Transaction.CreateIndex.removed_indices:type_name -> lance.table.IndexMetadata
	35, // 25: lance.table.Transaction.Rewrite.old_fragments:type_name -> lance.table.DataFragment
	35, // 26: lance.table.Transaction.Rewrite.new_fragments:type_name -> lance.table.DataFragment
	27, // 27: lance.table.Transaction.Rewrite.groups:type_name -> lance.table.Transaction.Rewrite.RewriteGroup
	26, // 28: lance.table.Transaction.Rewrite.rewritten_indices:type_name -> lance.table.Transaction.Rewrite.RewrittenIndex
	35, // 29: lance.table.Transaction.Merge.fragments:type_name -> lance.table.DataFragment
	36, // 30: lance.table.Transaction.Merge.schema:type_name -> lance.file.Field
	28, // 31: lance.table.Transaction.Merge.schema_metadata:type_name -> lance.table.Transaction.Merge.SchemaMetadataEntry
	36, // 32: lance.table.Transaction.Project.schema:type_name -> lance.file.Field
	13, // 33: lance.table.Transaction.KeyExistenceFilter.exact:type_name -> lance.table.Transaction.ExactKeySetFilter
	14, // 34: lance.table.Transaction.KeyExistenceFilter.bloom:type_name -> lance.table.Transaction.BloomFilter
	35, // 35: lance.table.Transaction.Update.updated_fragments:type_name -> lance.table.DataFragment
	35, // 36: lance.table.Transaction.Update.new_fragments:type_name -> lance.table.DataFragment
	39, // 37: lance.table.Transaction.Update.merged_generations:type_name -> lance.table.MergedGeneration
	0,  // 38: lance.table.Transaction.Update.update_mode:type_name -> lance.table.Transaction.UpdateMode
	15, // 39: lance.table.Transaction.Update.inserted_rows:type_name -> lance.table.Transaction.KeyExistenceFilter
	17, // 40: lance.table.Transaction.UpdateMap.update_entries:type_name -> lance.table.Transaction.UpdateMapEntry
	18, // 41: lance.table.Transaction.UpdateConfig.config_updates:type_name -> lance.table.Transaction.UpdateMap
	18, // 42: lance.table.Transaction.UpdateConfig.table_metadata_updates:type_name -> lance.table.Transaction.UpdateMap
	18, // 43: lance.table.Transaction.UpdateConfig.schema_metadata_updates:type_name -> lance.table.Transaction.UpdateMap
	29, // 44: lance.table.Transaction.UpdateConfig.field_metadata_updates:type_name -> lance.table.Transaction.UpdateConfig.FieldMetadataUpdatesEntry
	30, // 45: lance.table.Transaction.UpdateConfig.upsert_values:type_name -> lance.table.Transaction.UpdateConfig.UpsertValuesEntry
	31, // 46: lance.table.Transaction.UpdateConfig.schema_metadata:type_name -> lance.table.Transaction.UpdateConfig.SchemaMetadataEntry
	32, // 47: lance.table.Transaction.UpdateConfig.field_metadata:type_name -> lance.table.Transaction.UpdateConfig.FieldMetadataEntry
	40, // 48: lance.table.Transaction.DataReplacementGroup.new_file:type_name -> lance.table.DataFile
	20, // 49: lance.table.Transaction.DataReplacement.replacements:type_name -> lance.table.Transaction.DataReplacementGroup
	39, // 50: lance.table.Transaction.UpdateMemWalState.merged_generations:type_name -> lance.table.MergedGeneration
	37, // 51: lance.table.Transaction.UpdateBases.new_bases:type_name -> lance.table.BasePath
	41, // 52: lance.table.Transaction.Rewrite.RewrittenIndex.old_id:type_name -> lance.table.UUID
	41, // 53: lance.table.Transaction.Rewrite.RewrittenIndex.new_id:type_name -> lance.table.UUID
	42, // 54: lance.table.Transaction.Rewrite.RewrittenIndex.new_index_details:type_name -> google.protobuf.Any
	35, // 55: lance.table.Transaction.Rewrite.RewriteGroup.old_fragments:type_name -> lance.table.DataFragment
	35, // 56: lance.table.Transaction.Rewrite.RewriteGroup.new_fragments:type_name -> lance.table.DataFragment
	18, // 57: lance.table.Transaction.UpdateConfig.FieldMetadataUpdatesEntry.value:type_name -> lance.table.Transaction.UpdateMap
	33, // 58: lance.table.Transaction.UpdateConfig.FieldMetadataEntry.value:type_name -> lance.table.Transaction.UpdateConfig.FieldMetadataUpdate
	34, // 59: lance.table.Transaction.UpdateConfig.FieldMetadataUpdate.metadata:type_name -> lance.table.Transaction.UpdateConfig.FieldMetadataUpdate.MetadataEntry
	60, // [60:60] is the sub-list for method output_type
	60, // [60:60] is the sub-list for method input_type
	60, // [60:60] is the sub-list for extension type_name
	60, // [60:60] is the sub-list for extension extendee
	0,  // [0:60] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	file_file_proto_init()
	file_table_proto_init()
	file_transaction_proto_msgTypes[0].OneofWrappers = []any{
		(*Transaction_Append_)(nil),
		(*Transaction_Delete_)(nil),
		(*Transaction_Overwrite_)(nil),
		(*Transaction_CreateIndex_)(nil),
		(*Transaction_Rewrite_)(nil),
		(*Transaction_Merge_)(nil),
		(*Transaction_Restore_)(nil),
		(*Transaction_ReserveFragments_)(nil),
		(*Transaction_Update_)(nil),
		(*Transaction_Project_)(nil),
		(*Transaction_UpdateConfig_)(nil),
		(*Transaction_DataReplacement_)(nil),
		(*Transaction_UpdateMemWalState_)(nil),
		(*Transaction_Clone_)(nil),
		(*Transaction_UpdateBases_)(nil),
	}
	file_transaction_proto_msgTypes[11].OneofWrappers = []any{}
	file_transaction_proto_msgTypes[14].OneofWrappers = []any{
		(*Transaction_KeyExistenceFilter_Exact)(nil),
		(*Transaction_KeyExistenceFilter_Bloom)(nil),
	}
	file_transaction_proto_msgTypes[15].OneofWrappers = []any{}
	file_transaction_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
